#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2711 THIS_HMM_HIT[TIGR00026]
rule "2711|F420-binding GO term by HMM TIGR00026"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00026' )
	gene1 : Feature( featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2711");
	a.addGoIds("GO:0070967");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end