#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2715 THIS_HMM_HIT[PF00158] && THIS_HMM_HIT[PF01590] && THIS_HMM_HIT[PF02954]
rule "2715|GAF-modulated sigma-54-dependent Fis-type transcriptional regulator by HMM domain trio."
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF00158' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='PF01590' )
	hmm_hit3 : HmmHit( program=='hmm', hitId=='PF02954' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId, featureId == hmm_hit3.queryId )


then
	Annotation a = new Annotation("2715");
	a.setCommonName("GAF-modulated sigma-54-dependent Fis-type transcriptional regulator");
	a.addGoIds("GO:0003700,GO:0005515,GO:0006355");
	a.setRoleIds("261,263");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end