#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2576 DEFAULT_METHOD[GB|ABS34100.1]
rule "2576|flagellar glycosylation island glycosyltransferase, CBO2703 family"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABS34100.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2576");
	a.setCommonName("flagellar glycosylation island glycosyltransferase, CBO2703 family");
	a.setEcNumbers("2.4.1.-");
	a.addGoIds("GO:0000271,GO:0016757");
	a.setRoleIds("91");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end