#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2648 THIS_BLAST_HIT[GB|AAY93880.1, 550, 94, 92, 70, 3, 0] || (THIS_HMM_HIT[TIGR00905] && NEAR_HMM_HIT[6000, TIGR01078] && NEAR_HMM_HIT[6000, TIGR00658] &&  NEAR_HMM_HIT[6000, TIGR00746])
rule "2648|arginine/ornithine antiporter"
no-loop true
when
	(or
		(and
			blast_hit : BlastHit( program=='blastp', 
					hitId=='GB|AAY93880.1', 
					bitScore >= 550, 
					hitPercentLength >= 94, 
					queryPercentLength >= 92, 
					percentIdentity >= 70, 
					hitQueryLengthRatio <= 3 )
			gene1 : Feature( featureId == blast_hit.queryId )
		)
		(and
			hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00905' )
			hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01078' )
			hmm_hit3 : HmmHit( program=='hmm', hitId=='TIGR00658' )
			hmm_hit4 : HmmHit( program=='hmm', hitId=='TIGR00746' )
			gene1 : Feature( featureId == hmm_hit1.queryId )
			gene2 : Feature( featureId == hmm_hit2.queryId, eval(gene2.isWithin(gene1, 6000)) )
			gene3 : Feature( featureId == hmm_hit3.queryId, eval(gene3.isWithin(gene2, 6000)) )
			gene4 : Feature( featureId == hmm_hit4.queryId, eval(gene4.isWithin(gene3, 6000)) )
		)
	)
then
	Annotation a = new Annotation("2648");
	a.setCommonName("arginine/ornithine antiporter");
	a.setEcNumbers(" ");
	a.setGeneSymbol("arcD");
	a.addGoIds("GO:0005887,GO:0015171");
	a.addRoleIds("142");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end