#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2427 DEFAULT_METHOD[RF|YP_001780854.1] && GEN_STATE[GenProp0078, Firmicutes]
rule "2427|CotJB protein after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001780854.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	txn1 : Taxon( parentNames contains 'Firmicutes' )
	gene1 : Feature( taxon == txn1, featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2427");
	a.setCommonName("CotJB protein");
	a.setGeneSymbol("cotJB");
	a.setGoIds("GO:0003674,GO:0034301");
	a.setRoleIds("705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end