#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2667 THIS_HMM_HIT[TIGR02401] && THIS_HMM_HIT[TIGR00217]
rule "2667|4-alpha-glucanotransferase/malto-oligosyltrehalose synthase"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02401' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR00217' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2667");
	a.setCommonName("4-alpha-glucanotransferase/malto-oligosyltrehalose synthase");
	a.setEcNumbers("2.4.1.25 5.4.99.15");
	a.setGeneSymbol("malQ/treY");
	a.setGoIds("GO:0005992,GO:0004134,GO:0047470,GO:0005980");
	a.setRoleIds("90,105");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end