#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2468 DEFAULT_METHOD[ RF|YP_001781423.1]
rule "2468|sporulation transcription factor Spo0A"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781423.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2468");
	a.setCommonName("sporulation transcription factor Spo0A");
	a.setEcNumbers(" ");
	a.setGeneSymbol("spo0A");
	a.setGoIds("GO:0000156,GO:0000160,GO:0006355,GO:0030436,GO:0042173");
	a.setRoleIds("699,705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end