#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2400 THIS_HMM_HIT[TIGR02198] && THIS_HMM_HIT[TIGR02199]
rule "2400|bifunctional protein HldE"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02198' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02199' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2400");
	a.setCommonName("bifunctional protein HldE");
	a.setEcNumbers("2.7.1.- 2.7.7.-");
	a.setGeneSymbol("hldE");
	a.setGoIds("GO:0009244,GO:0016773,GO:0016779");
	a.setRoleIds("90");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end