#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2393 THIS_HMM_HIT[TIGR00476] && GEN_PROP[GenProp0692, 0.7]
rule "2393|selenide, water dikinase: GO terms for selenouridine"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00476' )
	genprop1 : GenomeProperty( this['id'] == 'GenProp0692', this['value'] >= 0.7 )
	gene1 : Feature( properties contains genprop1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2393");
	a.addGoIds("GO:0004756,GO:0070329");
	a.addRoleIds("168");
	a.setConfidence(99);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end