#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2440 DEFAULT_METHOD[GB|ABS39976.1]
rule "2440|sulfite reductase, subunit A after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABS39976.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2440");
	a.setCommonName("sulfite reductase, subunit A");
	a.setEcNumbers("1.8.-.-");
	a.setGeneSymbol("asrA");
	a.setGoIds("GO:0006790,GO:0009055,GO:0016002");
	a.setRoleIds("106");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end