#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2611 THIS_HMM_HIT[TIGR01361] && THIS_HMM_HIT[TIGR01801]
rule "2611|chorismate mutase/phospho-2-dehydro-3-deoxyheptonate aldolase"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01361' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01801' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2611");
	a.setCommonName("chorismate mutase/phospho-2-dehydro-3-deoxyheptonate aldolase");
	a.setEcNumbers("5.4.99.5 2.5.1.54");
	a.setGeneSymbol("aroAF");
	a.setGoIds("GO:0003849,GO:0009423,GO:0004106");
	a.setRoleIds("70");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end