#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2458 DEFAULT_METHOD[GB|ABS40086.1]
rule "2458|streptolysin associated protein SagD after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABS40086.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2458");
	a.setCommonName("streptolysin associated protein SagD");
	a.setEcNumbers(" ");
	a.setGeneSymbol("sagD");
	a.setGoIds("GO:0009405,GO:0015465");
	a.setRoleIds("187");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end