#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2553 DEFAULT_METHOD[GB|AAF81073.1] && GEN_STATE[GenProp0078, Proteobacteria]
rule "2553|putative transmembrane regulator PrtR"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAF81073.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	txn1 : Taxon( parentNames contains 'Proteobacteria' )
	gene1 : Feature( taxon == txn1, featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2553");
	a.setCommonName("putative transmembrane regulator PrtR");
	a.setEcNumbers(" ");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0030528,GO:0051090");
	a.setRoleIds("263");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end