#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2330 THIS_HMM_HIT[TIGR00165] && GEN_STATE[GenProp0006,Bacteria]
rule "2330|ribosomal protein S18, rpsR by HMM in superkingdom BACTERIA"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00165' )
	txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2330");
	a.setCommonName("30S ribosomal protein S18");
	a.setEcNumbers(" ");
	a.setGeneSymbol("rpsR");
	a.setGoIds("GO:0003735,GO:0006412,GO:0022627");
	a.setRoleIds("158");
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end