#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2522 DEFAULT_METHOD[GB|CAB38127.2]
rule "2522|D-proline reductase, PrdB subunit, selenocysteine-containing"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|CAB38127.2', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2522");
	a.setCommonName("D-proline reductase, PrdB subunit, selenocysteine-containing");
	a.setEcNumbers("1.21.4.1");
	a.setGeneSymbol("prdB");
	a.setGoIds("GO:0006562,GO:0050002");
	a.setRoleIds("109");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end