#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2537 DEFAULT_METHOD[GB|ABS41906.1]
rule "2537|putative F-pilin acetylation protein TraX after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABS41906.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2537");
	a.setCommonName("putative F-pilin acetylation protein TraX");
	a.setEcNumbers(" ");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0000746,GO:0006474,GO:0070258");
	a.setRoleIds("91,702");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end