#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2512 DEFAULT_METHOD[SP|P45693]
rule "2512|stage V sporulation protein S"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|P45693', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2512");
	a.setCommonName("stage V sporulation protein S");
	a.setEcNumbers(" ");
	a.setGeneSymbol("spoVS");
	a.setGoIds("GO:0000917,GO:0030435");
	a.setRoleIds("705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end