#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2487 DEFAULT_METHOD[GB|ABS41826.1]
rule "2487|Trk system potassium uptake protein TrkH after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABS41826.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2487");
	a.setCommonName("Trk system potassium uptake protein TrkH");
	a.setEcNumbers(" ");
	a.setGeneSymbol("trkH");
	a.setGoIds("GO:0006813,GO:0015079");
	a.setRoleIds("145");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end