#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2388 THIS_BLAST_HIT[RF|NP_844922.1, 160, 90, 90, 80, 5, 0]
rule "2388|exosporium protein K"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|NP_844922.1', 
				bitScore >= 160, 
				hitPercentLength >= 90, 
				queryPercentLength >= 90, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2388");
	a.setCommonName("exosporium protein K");
	a.setEcNumbers(" ");
	a.setGeneSymbol("exsK");
	a.setGoIds("GO:0043592,GO:0003674,GO:0008150");
	a.setRoleIds("705");
	a.setConfidence(96);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end