#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2571 DEFAULT_METHOD[RF|ZP_03568752.1] && GEN_STATE[GenProp0006, Bacteria]
rule "2571|LPXTG-motif cell wall anchored repeat protein"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|ZP_03568752.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2571");
	a.setCommonName("LPXTG-motif cell wall anchored repeat protein");
	a.setEcNumbers(" ");
	a.addGoIds("GO:0005618");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end