#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2646 THIS_BLAST_HIT[GB|AAC73787.1, 1200, 95, 92, 80, 5, 0] || (NEAR_HMM_HIT[1000, TIGR00905] && THIS_BLAST_HIT[GB|AAC73787.1, 950, 95, 92, 65, 5, 0])
rule "2646|ornithine decarboxylase SpeF"
no-loop true
when
	(or
		(and
			hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00905' )
			blast_hit1 : BlastHit( program=='blastp', 
					hitId=='GB|AAC73787.1', 
					bitScore >= 950, 
					hitPercentLength >= 95, 
					queryPercentLength >= 92, 
					percentIdentity >= 65, 
					hitQueryLengthRatio <= 5 )
			gene1 : Feature( featureId == blast_hit1.queryId )
			gene2 : Feature( featureId == hmm_hit1.queryId, eval(gene2.isWithin(gene1, 1000)) )
		)
		(and
			blast_hit2 : BlastHit( program=='blastp', 
					hitId=='GB|AAC73787.1', 
					bitScore >= 1200, 
					hitPercentLength >= 95, 
					queryPercentLength >= 92, 
					percentIdentity >= 80, 
					hitQueryLengthRatio <= 5 )
			gene1 : Feature( featureId == blast_hit2.queryId )
		)
	)

then
	Annotation a = new Annotation("2646");
	a.setCommonName("ornithine decarboxylase SpeF");
	a.setEcNumbers("4.1.1.17");
	a.setGeneSymbol("speF");
	a.addGoIds("GO:0004586,GO:0006591");
	a.addRoleIds("149");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end