#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2305 THIS_HMM_HIT[TIGR01067] && GEN_STATE[GenProp0006,Bacteria]
rule "2305|50S ribosomal protein L14 by HMM in BACTERIA"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01067' )
	txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2305");
	a.setCommonName("50S ribosomal protein L14");
	a.setEcNumbers(" ");
	a.setGeneSymbol("rplN");
	a.setGoIds("GO:0003735,GO:0006412,GO:0022625,GO:0019843,GO:0005515");
	a.setRoleIds("158");
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end