#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2686 THIS_HMM_HIT[PF02909] && THIS_HMM_HIT[PF00440]
rule "2686|substrate binding-dependent transcriptional regulator, TetR family"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF02909' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='PF00440' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2686");
	a.setCommonName("substrate binding-dependent transcriptional regulator, TetR family");
	a.setGoIds("GO:0051606,GO:0003700,GO:0006355,GO:0043565");
	a.setRoleIds("261");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end