#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2430 DEFAULT_METHOD[GB|ACA54161.1]
rule "2430|ABC transporter, ATP-binding protein, SagG family after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA54161.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2430");
	a.setCommonName("heterocyclic bacteriocin ABC transporter, ATP-binding protein SagG");
	a.setEcNumbers(" ");
	a.setGeneSymbol("sagG");
	a.setGoIds("GO:0006810,GO:0009405,GO:0042626");
	a.setRoleIds("147,187");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end