#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2639 THIS_BLAST_HIT[GB|ABG86187.1, 1600, 95, 92, 70, 3, 0] && NEAR_HMM_HIT[100,TIGR00541]
rule "2639|putative histidine/histamine antiporter by genomic context"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABG86187.1', 
				bitScore >= 1600, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 70, 
				hitQueryLengthRatio <= 3 )
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00541' )
	gene1 : Feature( featureId == blast_hit1.queryId )
	gene2 : Feature( featureId == hmm_hit1.queryId, eval(gene2.isWithin(gene1, 100)) )


then
	Annotation a = new Annotation("2639");
	a.setCommonName("putative histidine/histamine antiporter");
	a.setEcNumbers(" ");
	a.addGoIds("GO:0015297,GO:0006865,GO:0015171");
	a.setRoleIds("142");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end