#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2624 THIS_HMM_HIT[TIGR01554] && THIS_HMM_HIT[TIGR01543]
rule "2624|prohead protease/major capsid protein, phage HK97 family"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01554' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01543' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2624");
	a.setCommonName("prohead protease/major capsid protein, phage HK97 family");
	a.setEcNumbers(" ");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0005198,GO:0008233,GO:0019012,GO:0019068");
	a.setRoleIds("152");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end