#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2661 THIS_BLAST_HIT[GB|BAB21508.1, 300, 85, 85, 50, 5, 0]
rule "2661|protein-glutaminase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|BAB21508.1', 
				bitScore >= 300, 
				hitPercentLength >= 85, 
				queryPercentLength >= 85, 
				percentIdentity >= 50, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2661");
	a.setCommonName("protein-glutaminase");
	a.setEcNumbers("3.5.1.-");
	a.setGeneSymbol("prgA");
	a.addGoIds("GO:0016811");
	a.addRoleIds("189");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end