#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2718 THIS_BLAST_HIT[GB|AAK76014.1, 450, 95, 92, 75, 5, 0]
rule "2718|lantibiotic system transcriptional regulator"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAK76014.1', 
				bitScore >= 450, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 75, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2718");
	a.setCommonName("lantibiotic system transcriptional regulator");
	a.addGoIds("GO:0003677,GO:0006355");
	a.setRoleIds("94,261");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end