#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2406 THIS_BLAST_HIT[GB|AAL73951.1, 75, 90, 90, 75, 3, 0]
rule "2406|cell-cell signaling protein PapR"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAL73951.1', 
				bitScore >= 75, 
				hitPercentLength >= 90, 
				queryPercentLength >= 90, 
				percentIdentity >= 75, 
				hitQueryLengthRatio <= 3 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2406");
	a.setCommonName("cell-cell signalling protein PapR");
	a.setEcNumbers(" ");
	a.setGeneSymbol("papR");
	a.setGoIds("GO:0005576,GO:0008134,GO:0052100");
	a.setRoleIds("710");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end