#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2551 DEFAULT_METHOD[RF|YP_001783274.1]
rule "2551|sporulation initiation inhibitor protein Soj"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001783274.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2551");
	a.setCommonName("sporulation initiation inhibitor protein Soj");
	a.setEcNumbers(" ");
	a.setGeneSymbol("soj");
	a.setGoIds("GO:0016887,GO:0030436,GO:0042174");
	a.setRoleIds("129,705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end