#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2298 THIS_HMM_HIT[TIGR01023] && GEN_STATE[GenProp0006,Bacteria]
rule "2298|50S ribosomal protein L33 by HMM in BACTERIA"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01023' )
	txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2298");
	a.setCommonName("50S ribosomal protein L33");
	a.setEcNumbers(" ");
	a.setGeneSymbol("rpmG");
	a.setGoIds("GO:0003735,GO:0006412,GO:0022625");
	a.setRoleIds("158");
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end