#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2339 DEFAULT_METHOD[SP|O07623]
rule "2339|subtilosin-A by default method"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|O07623', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2339");
	a.setCommonName("subtilosin-A");
	a.setEcNumbers(" ");
	a.setGeneSymbol("sboA");
	a.setRoleIds("94");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end