#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2568 DEFAULT_METHOD[SP|O32221]
rule "2568|copper chaperone CopZ"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|O32221', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2568");
	a.setCommonName("copper chaperone CopZ");
	a.setEcNumbers(" ");
	a.setGeneSymbol("copZ");
	a.setGoIds("GO:0005507,GO:0006825");
	a.setRoleIds("96,145");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end