#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2449 DEFAULT_METHOD[GB|EDK35753.1]
rule "2449|spore maturation protein B after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|EDK35753.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2449");
	a.setCommonName("spore maturation protein B");
	a.setEcNumbers(" ");
	a.setGeneSymbol("spmB");
	a.setGoIds("GO:0016021,GO:0034301");
	a.setRoleIds("705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end