#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2353 THIS_HMM_HIT[TIGR00054] && GEN_STATE[GenProp0081, Bacillaceae]
rule "2353|RIP metalloprotease RasP"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00054' )
	txn1 : Taxon( parentNames contains 'Bacillaceae' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2353");
	a.setCommonName("RIP metalloprotease RasP");
	a.setGeneSymbol("rasP");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end