#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2453 DEFAULT_METHOD[GB|BAB16890.1]
rule "2453|chitinase A MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|BAB16890.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2453");
	a.setCommonName("chitinase A");
	a.setEcNumbers("3.2.1.14");
	a.setGeneSymbol("chiA");
	a.setGoIds("GO:0000272,GO:0004568");
	a.setRoleIds("105");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end