#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2356 DEFAULT_METHOD[SP|P32397] && GEN_STATE[GenProp0082, Bacillus]
rule "2356|protoporphyrinogen oxidase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|P32397', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	txn1 : Taxon( parentNames contains 'Bacillus' )
	gene1 : Feature( taxon == txn1, featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2356");
	a.setCommonName("protoporphyrinogen oxidase");
	a.setEcNumbers("1.3.3.4");
	a.setGoIds("GO:0004729,GO:0006779");
	a.setRoleIds("79");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end