#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2355 THIS_HMM_HIT[TIGR00239] && GEN_STATE[GenProp0082, Bacillus]
rule "2-oxoglutarate dehydrogenase, E1 component"
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00239' )
	 and
	 txn1 : Taxon( parentNames contains 'Bacillus' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2355");
	 a.setEcNumbers("1.2.4.2");
	 a.setCommonName("2-oxoglutarate dehydrogenase, E1 component");
	 a.setGeneSymbol("odhA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end