#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2387 THIS_BLAST_HIT[GB|CAD56871.1, 125, 60, 60, 80, 20, 1] && THIS_HMM_HIT[TIGR03720]
rule "spore surface glycoprotein BclA"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|CAD56871.1', 
			bitScore >= 125,
			hitPercentLength >= 60,
			queryPercentLength >= 60,  
			percentIdentity >= 80,
			hitQueryLengthRatio <= 20 
		)
	 and
	 hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR03720' )
	gene1 : Feature( featureId == blast_hit1.queryId, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2387");
	 a.setGoIds("GO:0003674,GO:0005575,GO:0008150");
	 a.setRoleIds("705");
	 a.setCommonName("spore surface glycoprotein BclA");
	 a.setGeneSymbol("bclA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end