#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2546 DEFAULT_METHOD[GB|ABS40012.1]
rule "cadmium resistance transporter CadD after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABS40012.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2546");
	 a.setGoIds("GO:0015086,GO:0016021,GO:0046686");
	 a.setRoleIds("96,145");
	 a.setCommonName("cadmium resistance transporter CadD");
	 a.setGeneSymbol("cadD");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end