#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2356 DEFAULT_METHOD[SP|P32397] && GEN_STATE[GenProp0082, Bacillus]
rule "protoporphyrinogen oxidase"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P32397', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	 and
	 txn1 : Taxon( parentNames contains 'Bacillus' )
	gene1 : Feature( taxon == txn1, featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2356");
	 a.setGoIds("GO:0004729,GO:0006779");
	 a.setEcNumbers("1.3.3.4");
	 a.setRoleIds("79");
	 a.setCommonName("protoporphyrinogen oxidase");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end