#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2554 DEFAULT_METHOD[GB|ACA55208.1]
rule "2554|cardiolipin synthase after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA55208.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2554");
	a.setCommonName("cardiolipin synthase");
	a.setEcNumbers("2.7.8.-");
	a.setGeneSymbol("cls");
	a.setGoIds("GO:0004620,GO:0008808,GO:0009395");
	a.setRoleIds("176");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end