#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2568 DEFAULT_METHOD[SP|O32221]
rule "copper chaperone CopZ"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|O32221', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2568");
	 a.setGoIds("GO:0005507,GO:0006825");
	 a.setRoleIds("96,145");
	 a.setCommonName("copper chaperone CopZ");
	 a.setGeneSymbol("copZ");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end