#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2419 DEFAULT_METHOD[RF|YP_001386645.1]
rule "putative arsenical resistance operon repressor ArsR after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001386645.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2419");
	 a.setGoIds("GO:0006355,GO:0016564,GO:0046685");
	 a.setRoleIds("96,261");
	 a.setCommonName("putative arsenical resistance operon repressor ArsR");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end