#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2538 DEFAULT_METHOD[RF|YP_001781859.1]
rule "putative RNAase regulator"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001781859.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2538");
	 a.setGoIds("GO:0005515,GO:0030234,GO:0043086");
	 a.setRoleIds("129");
	 a.setCommonName("putative RNase regulator");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end