#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2676 THIS_BLAST_HIT[GB:AAT29114.1, 140, 95, 92, 80, 3, 1]
rule "2676|transition state transcriptional regulatory protein AbrB"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB:AAT29114.1', 
				bitScore >= 140, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 3 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2676");
	a.setCommonName("transition state transcriptional regulatory protein AbrB");
	a.setGeneSymbol("abrB");
	a.addGoIds("GO:0003700,GO:0006355,GO:0016566,GO:0030435");
	a.addRoleIds("261,705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end