#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2489 DEFAULT_METHOD[GB|CAA63429.1]
rule "rubrerythrin after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|CAA63429.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2489");
	 a.setGoIds("GO:0006118,GO:0009055");
	 a.setRoleIds("112");
	 a.setCommonName("rubrerythrin");
	 a.setGeneSymbol("rbr");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end