#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2549 DEFAULT_METHOD[GB|ACA53992.1]
rule "oxalate decarboxylase after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA53992.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2549");
	 a.setGoIds("GO:0015942,GO:0046564");
	 a.setEcNumbers("4.1.1.2");
	 a.setRoleIds("184");
	 a.setCommonName("oxalate decarboxylase");
	 a.setGeneSymbol("oxdD");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end