#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2587 THIS_HMM_HIT[TIGR01240] && THIS_HMM_HIT[TIGR02150]
rule "diphosphomevalonate decarboxylase/isopentenyl-diphosphate delta-isomerase"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01240' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02150' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2587");
	 a.setGoIds("GO:0004163,GO:0004452,GO:0005524,GO:0008299,GO:0019287");
	 a.setEcNumbers("4.1.1.33 5.3.3.2");
	 a.setCommonName("diphosphomevalonate decarboxylase/isopentenyl-diphosphate delta-isomerase");
	 a.setRoleIds("76");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end