#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2598 DEFAULT_METHOD[GB|CAL84271.1]
rule "flagellar glycosylation island glycosyltransferase, CBO2710 family"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|CAL84271.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2598");
	 a.setGoIds("GO:0000271,GO:0016757");
	 a.setEcNumbers("2.4.1.-");
	 a.setRoleIds("90,91");
	 a.setCommonName("flagellar glycosylation island glycosyltransferase, CBO2710 family");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end