#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2434 DEFAULT_METHOD[GB|ACA53790.1]
rule "pyridoxal-phosphate-dependent aminotransferase family after MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA53790.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2434");
	 a.setGoIds("GO:0008483,GO:0008152");
	 a.setEcNumbers("2.6.1.-");
	 a.setRoleIds("71");
	 a.setCommonName("pyridoxal-phosphate-dependent aminotransferase");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end