#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2409 THIS_BLAST_HIT[SP|P35157, 200, 85, 85, 50, 5, 0] && NEAR_BLAST_HIT[200, SP|P35150, 275, 95, 92, 40, 5, 0]
rule "2409|spore maturation protein A"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|P35157', 
				bitScore >= 200, 
				hitPercentLength >= 85, 
				queryPercentLength >= 85, 
				percentIdentity >= 50, 
				hitQueryLengthRatio <= 5 )
	blast_hit2 : BlastHit( program=='blastp', 
				hitId=='SP|P35150', 
				bitScore >= 275, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 40, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit2.queryId, featureId == blast_hit1.queryId )
	gene2 : Feature( eval(gene2.isWithin(gene1, 200)) )


then
	Annotation a = new Annotation("2409");
	a.setCommonName("spore maturation protein A");
	a.setGeneSymbol("spmA");
	a.addGoIds("GO:0034301");
	a.addRoleIds("705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end