#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2486 DEFAULT_METHOD[GB|ABS40789.1]
rule "Trk system potassium uptake protein TrkA after MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABS40789.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2486");
	 a.setGoIds("GO:0006813,GO:0015079");
	 a.setRoleIds("145");
	 a.setCommonName("Trk system potassium uptake protein TrkA");
	 a.setGeneSymbol("trkA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end