#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2716 THIS_HMM_HIT[TIGR01445] && THIS_HMM_HIT[TIGR01443]
rule "2716|Assertion that gene has intein"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01445' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01443' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2716");
	has_intein_prop : Map( this['type']: 'gene_attribute', this['has_intein']: 1 );
	gene1.addProperty(has_intein_prop);
	a.setSpecificity(SpecificityType.ASSERT_GENE);
	insert(has_intein_prop);
end