#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2485 DEFAULT_METHOD[GB|ACA55714.1]
rule "2485|dimethylamine corrinoid protein"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA55714.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2485");
	a.setCommonName("dimethylamine corrinoid protein");
	a.setEcNumbers(" ");
	a.setGeneSymbol("mtbC");
	a.setGoIds("GO:0008168,GO:0015948");
	a.setRoleIds("159");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end