#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2654 NEAR_HMM_HIT[1000, TIGR03811] && THIS_BLAST_HIT[GB|AAO80460.1, 550, 95, 92, 60, 5, 0]
rule "2654|tyrosine-tyramine antiporter"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR03811' )
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAO80460.1', 
				bitScore >= 550, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 60, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == hmm_hit1.queryId )
	gene2 : Feature( featureId == blast_hit1.queryId, eval(gene2.isWithin(gene1, 1000)) )


then
	Annotation a = new Annotation("2654");
	a.setCommonName("tyrosine-tyramine antiporter");
	a.setGoIds("GO:0015300");
	a.setRoleIds("142");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end