#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2337 DEFAULT_METHOD[OMNI|NTL01CV3271]
rule "2337|default-mode rule, to be part of violacein biosynthesis GenProp0823"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='OMNI|NTL01CV3271', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2337");
	a.setCommonName("violacein biosynthesis enzyme VioD");
	a.setEcNumbers("1.-.-.-");
	a.setGeneSymbol("vioD");
	a.setRoleIds("94");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end