#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2581 THIS_BLAST_HIT[GB|ABP53663.1, 400, 85, 85, 50, 10, 0] && THIS_HMM_HIT[TIGR01167]
rule "LPXTG-anchored RCC1-type repeat protein"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABP53663.1', 
			bitScore >= 400,
			hitPercentLength >= 85,
			queryPercentLength >= 85,  
			percentIdentity >= 50,
			hitQueryLengthRatio <= 10 
		)
	 and
	 hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01167' )
	gene1 : Feature( featureId == blast_hit1.queryId, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2581");
	 a.setRoleIds("88");
	 a.setCommonName("LPXTG-anchored RCC1-type repeat protein");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end