#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2346 THIS_HMM_HIT[TIGR03652] && GEN_STATE[GenProp0008, YES] && GEN_STATE[GenProp0006, Bacteria]
rule "2346|iron-sulfur cluster repair protein RIC - add pathogen terms if pathogen"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR03652' )
	txn1 : Taxon( parentNames contains 'YES' )
	txn2 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, taxon == txn2, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2346");
	a.addGoIds("GO:0052059");
	a.addRoleIds("149");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end