#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2662 THIS_HMM_HIT[TIGR00017] && THIS_HMM_HIT[TIGR00018]
rule "bifunctional pantoate--beta-alanine ligase/cytidylate kinase"
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00017' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR00018' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2662");
	 a.setGoIds("GO:0004127,GO:0015949,GO:0004592,GO:0015940");
	 a.setEcNumbers("6.3.2.1 2.7.4.14");
	 a.setRoleIds("83,124");
	 a.setCommonName("bifunctional pantoate--beta-alanine ligase/cytidylate kinase");
	 a.setGeneSymbol("panC/cmk");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end