#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2522 DEFAULT_METHOD[GB|CAB38127.2]
rule "D-proline reductase, PrdB subunit, selenocysteine-containing"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|CAB38127.2', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2522");
	 a.setGoIds("GO:0006562,GO:0050002");
	 a.setEcNumbers("1.21.4.1");
	 a.setCommonName("D-proline reductase, PrdB subunit, selenocysteine-containing");
	 a.setRoleIds("109");
	 a.setGeneSymbol("prdB");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end