#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2385 THIS_BLAST_HIT[GB|AAM76786.1, 70, 90, 90, 70, 5, 0]
rule "exosporium protein G"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|AAM76786.1', 
			bitScore >= 70,
			hitPercentLength >= 90,
			queryPercentLength >= 90,  
			percentIdentity >= 70,
			hitQueryLengthRatio <= 5 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2385");
	 a.setGoIds("GO:0043592,GO:0003674,GO:0008150");
	 a.setRoleIds("705");
	 a.setCommonName("exosporium protein G");
	 a.setGeneSymbol("exsG");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end