#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2472 DEFAULT_METHOD[SP|P54935]
rule "glycine reductase complex component C, beta subunit after MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P54935', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2472");
	 a.setGoIds("GO:0006544,GO:0030699,GO:0030700");
	 a.setEcNumbers("1.21.4.2");
	 a.setRoleIds("109");
	 a.setCommonName("glycine reductase complex component C, beta subunit");
	 a.setGeneSymbol("grdC");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end