#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2432 DEFAULT_METHOD[RF|YP_001779892.1]
rule "2432|putative lysine-specific permease after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001779892.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2432");
	a.setCommonName("putative lysine-specific permease");
	a.setEcNumbers(" ");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0015189,GO:0015819,GO:0016021");
	a.setRoleIds("142");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.JOC_MGAT_SUBFAM);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end