#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2673 GEN_PROP[GenProp0038, 0.55] && THIS_HMM_HIT_UNIQUE[PF01227] && !GENOME_HMM_HIT[TIGR00063]
rule "GTP cyclohydrolase I when PF01227 hits but TIGR00063 misses, with GenProp support"
no-loop true
 when
	genprop1 : GenomeProperty( this['id'] == 'GenProp0038', this['value'] >= 0.55 )
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF01227' )
	gene1 : Feature( featureId == hmm_hit1.queryId, properties contains genprop1 )
	not HmmHit( program=='hmm', hitId=='TIGR00063', queryId == gene1.featureId )
	
 then
	 Annotation a = new Annotation("2673");
	 a.setGoIds("NULL");
	 a.setEcNumbers("3.5.4.16");
	 a.setRoleIds("78");
	 a.setCommonName("GTP cyclohydrolase I");
	 a.setGeneSymbol("folE");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end