#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2630 THIS_BLAST_HIT[GB|ABJ65006.1, 673, 85, 85, 63, 10, 0] && THIS_HMM_HIT[PF06458] && THIS_HMM_HIT[TIGR01167]
rule "2630|LPXTG-anchored MucBP-type repeat protein"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABJ65006.1', 
				bitScore >= 673, 
				hitPercentLength >= 85, 
				queryPercentLength >= 85, 
				percentIdentity >= 63, 
				hitQueryLengthRatio <= 10 )
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF06458' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01167' )
	gene1 : Feature( featureId == blast_hit1.queryId, featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2630");
	a.setCommonName("LPXTG-anchored MucBP-type repeat protein");
	a.setRoleIds("88");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end