#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2615 THIS_HMM_HIT[TIGR00399] && GENOME_HMM_HIT[TIGR00398] && !THIS_HMM_HIT[TIGR00398]
rule "methionyl-tRNA synthetase, beta subunit"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00399' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR00398' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	not HmmHit( program=='hmm', hitId=='TIGR00398', queryId == gene1.featureId )
	
 then
	 Annotation a = new Annotation("2615");
	 a.setGoIds("GO:0004825,GO:0006431");
	 a.setEcNumbers("6.1.1.10");
	 a.setCommonName("methionyl-tRNA synthetase, beta subunit");
	 a.setRoleIds("137");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end