#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2456 DEFAULT_METHOD[GB|ACA54656.1]
rule "2456|high-affinity branched-chain amino acid ABC transporter, permease protein"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA54656.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2456");
	a.setCommonName("high-affinity branched-chain amino acid ABC transporter, permease protein");
	a.setEcNumbers(" ");
	a.setGoIds("GO:0005887,GO:0015658,GO:0015803,GO:0042626,GO:0043192");
	a.setRoleIds("142");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end