#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2514 DEFAULT_METHOD[GB|ACA55601.1]
rule "2514|aspartate aminotransferase after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA55601.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2514");
	a.setCommonName("aspartate aminotransferase");
	a.setEcNumbers("2.6.1.1");
	a.setGeneSymbol("aspB");
	a.setGoIds("GO:0004069,GO:0006532");
	a.setRoleIds("71");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end