#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2308 THIS_HMM_HIT[TIGR01164] && GEN_STATE[GenProp0006,Bacteria]
rule "50S ribosomal protein L16 by HMM in BACTERIA"
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01164' )
	 and
	 txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2308");
	 a.setRoleIds("158");
	 a.setCommonName("50S ribosomal protein L16");
	 a.setGeneSymbol("rplP");
	 a.setGoIds("GO:0003735,GO:0006412,GO:0022625,GO:0019843");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end