#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2494 DEFAULT_METHOD[GB|ABS40524.1]
rule "2494|deoxyribonucleoside regulator"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABS40524.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2494");
	a.setCommonName("deoxyribonucleoside regulator");
	a.setEcNumbers(" ");
	a.setGeneSymbol("deoR");
	a.setGoIds("GO:0003700,GO:0006355");
	a.setRoleIds("261");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end