#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2682 THIS_BLAST_HIT[GB|BAA09026.1, 250, 95, 92, 30, 5, 0] && THIS_HMM_HIT[PF04234] && THIS_HMM_HIT[PF05425]
rule "2682|copper homeostasis protein CopCD"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|BAA09026.1', 
				bitScore >= 250, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 30, 
				hitQueryLengthRatio <= 5 )
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF04234' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='PF05425' )
	gene1 : Feature( featureId == blast_hit1.queryId, featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2682");
	a.setCommonName("copper homeostasis protein CopCD");
	a.setGeneSymbol("copCD");
	a.addGoIds("GO:0046688,GO:0005507");
	a.setRoleIds("145");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end