#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2520 DEFAULT_METHOD[RF|YP_001781847.1]
rule "2520|glycerate kinase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781847.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2520");
	a.setCommonName("glycerate kinase");
	a.setEcNumbers("2.7.1.31");
	a.setGeneSymbol("glxK");
	a.setGoIds("GO:0008887,GO:0009436");
	a.setRoleIds("184");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end