#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2504 DEFAULT_METHOD[GB|ACA56159.1]
rule "chemotaxis protein CheV after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA56159.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2504");
	 a.setGoIds("GO:0000156,GO:0000160,GO:0006935");
	 a.setRoleIds("188");
	 a.setCommonName("chemotaxis protein CheV");
	 a.setGeneSymbol("cheV");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end