#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2496 DEFAULT_METHOD[GB|ACA40331.1]
rule "major cold shock protein CspA"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA40331.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2496");
	 a.setGoIds("GO:0003677,GO:0006355,GO:0009409");
	 a.setRoleIds("149");
	 a.setCommonName("major cold shock protein CspA");
	 a.setGeneSymbol("cspA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end