#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2513 DEFAULT_METHOD[GB|AAO35849.1]
rule "2513|aspartate kinase 1"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAO35849.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2513");
	a.setCommonName("aspartate kinase");
	a.setEcNumbers("2.7.2.4");
	a.setGeneSymbol("dapG");
	a.setGoIds("GO:0004072,GO:0009089");
	a.setRoleIds("71");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end