#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2478 DEFAULT_METHOD[GB|ACA57104.1]
rule "2478|S-methyl-5-thioribose-1-phosphate isomerase after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA57104.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2478");
	a.setCommonName("S-methyl-5-thioribose-1-phosphate isomerase");
	a.setEcNumbers("5.3.1.23");
	a.setGeneSymbol("mtnA");
	a.setGoIds("GO:0019509,GO:0046523");
	a.setRoleIds("71");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end