#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2601 THIS_HMM_HIT[TIGR02365] && NEAR_HMM_HIT[1000,TIGR02364] && !THIS_HMM_HIT[TIGR02363]
rule "2601|PTS-dependent dihydroxyacetone kinase, DhaL subunit"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02365' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02364' )
	gene1 : Feature( featureId == hmm_hit1.queryId )
	gene2 : Feature( featureId == hmm_hit2.queryId, eval(gene2.isWithin(gene1, 1000)) )
	not HmmHit( program=='hmm', hitId=='TIGR02363', queryId == gene1.featureId )


then
	Annotation a = new Annotation("2601");
	a.setCommonName("PTS-dependent dihydroxyacetone kinase, DhaL subunit");
	a.setEcNumbers("2.7.-.-");
	a.setGeneSymbol("dhaL");
	a.setGoIds("GO:0006071,GO:0016772");
	a.setRoleIds("184");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end