#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2385 THIS_BLAST_HIT[GB|AAM76786.1, 70, 90, 90, 70, 5, 0]
rule "2385|exosporium protein G"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAM76786.1', 
				bitScore >= 70, 
				hitPercentLength >= 90, 
				queryPercentLength >= 90, 
				percentIdentity >= 70, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2385");
	a.setCommonName("exosporium protein G");
	a.setEcNumbers(" ");
	a.setGeneSymbol("exsG");
	a.setGoIds("GO:0043592,GO:0003674,GO:0008150");
	a.setRoleIds("705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end