#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2486 DEFAULT_METHOD[GB|ABS40789.1]
rule "2486|Trk system potassium uptake protein TrkA after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABS40789.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2486");
	a.setCommonName("Trk system potassium uptake protein TrkA");
	a.setEcNumbers(" ");
	a.setGeneSymbol("trkA");
	a.setGoIds("GO:0006813,GO:0015079");
	a.setRoleIds("145");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end