#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2384 THIS_BLAST_HIT[GB|AAN85821.1, 260, 95, 92, 87, 5, 0]
rule "2384|exosporium protein F"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAN85821.1', 
				bitScore >= 260, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 87, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2384");
	a.setCommonName("exosporium protein F");
	a.setGeneSymbol("exsF");
	a.addGoIds("GO:0043592,GO:0003674,GO:0008150");
	a.setRoleIds("705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end