#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2521 DEFAULT_METHOD[SP|Q0TPS3]
rule "polyribonucleotide nucleotidyltransferase"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|Q0TPS3', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2521");
	 a.setGoIds("GO:0004654,GO:0030420");
	 a.setEcNumbers("2.7.7.8");
	 a.setRoleIds("134");
	 a.setCommonName("polyribonucleotide nucleotidyltransferase");
	 a.setGeneSymbol("pnpA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end