#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2656 THIS_BLAST_HIT[GB|ABB67995.1, 300, 95, 85, 80, 3, 0]
rule "2656|glutamate-dependent acid resistance transcriptional activator GadE"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABB67995.1', 
				bitScore >= 300, 
				hitPercentLength >= 95, 
				queryPercentLength >= 85, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 3 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2656");
	a.setCommonName("glutamate-dependent acid resistance transcriptional activator GadE");
	a.setGeneSymbol("gadE");
	a.addGoIds("GO:0010447,GO:0016563,GO:0045893");
	a.addRoleIds("261");
	a.setConfidence(98);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end