#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2505 DEFAULT_METHOD[RF|YP_001781775.1]
rule "2505|2-enoate reductase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781775.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2505");
	a.setCommonName("2-enoate reductase");
	a.setEcNumbers("1.3.1.31");
	a.setGeneSymbol("enr");
	a.setGoIds("GO:0019665,GO:0047540");
	a.setRoleIds("109,110,114");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end