#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2488 DEFAULT_METHOD[RF|YP_001781563.1]
rule "2488|glycerol dehydrogenase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781563.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2488");
	a.setCommonName("glycerol dehydrogenase");
	a.setEcNumbers("1.1.1.6");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0006071,GO:0008888");
	a.setRoleIds("114");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end