#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2337 DEFAULT_METHOD[OMNI|NTL01CV3271]
rule "default-mode rule, to be part of violacein biosynthesis GenProp0823"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='OMNI|NTL01CV3271', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2337");
	 a.setCommonName("violacein biosynthesis enzyme VioD");
	 a.setGeneSymbol("vioD");
	 a.setEcNumbers("1.-.-.-");
	 a.setRoleIds("94");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end