#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2271 DEFAULT_METHOD[SP|P66817]
rule "DnaA initiator-associating protein DiaA, by DEFAULT_METHOD, should be above 85 percent"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P66817', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2271");
	 a.setCommonName("DnaA initiator-associating protein DiaA");
	 a.setGeneSymbol("diaA");
	 a.setRoleIds("132,261");
	 a.setGoIds("GO:0003677,GO:0005524,GO:0030174");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end