#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2569 DEFAULT_METHOD[SP|P0AGI8]
rule "2569|putative Trk system potassium uptake protein TrkA"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|P0AGI8', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2569");
	a.setCommonName("putative Trk system potassium uptake protein TrkA");
	a.setEcNumbers(" ");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0006813,GO:0015079");
	a.setRoleIds("145");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end