#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2400 THIS_HMM_HIT[TIGR02198] && THIS_HMM_HIT[TIGR02199]
rule "bifunctional protein HldE"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02198' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02199' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2400");
	 a.setGoIds("GO:0009244,GO:0016773,GO:0016779");
	 a.setEcNumbers("2.7.1.- 2.7.7.-");
	 a.setCommonName("bifunctional protein HldE");
	 a.setRoleIds("90");
	 a.setGeneSymbol("hldE");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end