#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2381 THIS_BLAST_HIT[GB|AAS41838.1, 500, 95, 95, 80, 5, 0]
rule "inosine-uridine preferring nucleoside hydrolase family protein"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|AAS41838.1', 
			bitScore >= 500,
			hitPercentLength >= 95,
			queryPercentLength >= 95,  
			percentIdentity >= 80,
			hitQueryLengthRatio <= 5 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2381");
	 a.addGoIds("GO:0043592");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end