#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2684 THIS_HMM_HIT[PF06192] && NEAR_HMM_HIT[1000, TIGR01409] && !NEAR_HMM_HIT[5000, TIGR02164]
rule "2684|TorD homolog that is not TorD itself because it is not near TorA."
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF06192' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01409' )
	not HmmHit( program=='hmm', hitId=='5000', queryId == gene2.featureId )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	gene2 : Feature( eval(gene2.isWithin(gene1, 1000)) )


then
	Annotation a = new Annotation("2684");
	a.setCommonName("TAT-signal peptide-binding chaperone, TorD family");
	a.setGeneSymbol("NULL");
	a.addGoIds("GO:0051082,GO:0043953");
	a.setRoleIds("95,97");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end