#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2495 DEFAULT_METHOD[RF|YP_001781593.1]
rule "2495|prolyl aminopeptidase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781593.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2495");
	a.setCommonName("prolyl aminopeptidase");
	a.setEcNumbers("3.4.11.5");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0006508,GO:0016804");
	a.setRoleIds("138");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end