#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2546 DEFAULT_METHOD[GB|ABS40012.1]
rule "2546|cadmium resistance transporter CadD after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABS40012.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2546");
	a.setCommonName("cadmium resistance transporter CadD");
	a.setEcNumbers(" ");
	a.setGeneSymbol("cadD");
	a.setGoIds("GO:0015086,GO:0016021,GO:0046686");
	a.setRoleIds("96,145");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end