#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2165 THIS_BLAST_HIT[GB|CAL20547.1, 350, 95, 95, 80, 4, 1]
rule "yersiniabactin biosynthesis thioesterase YbtT, BLASTP"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|CAL20547.1', 
			bitScore >= 350,
			hitPercentLength >= 95,
			queryPercentLength >= 95,  
			percentIdentity >= 80,
			hitQueryLengthRatio <= 4 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2165");
	 a.setCommonName("yersiniabactin biosynthesis thioesterase YbtT");
	 a.setGeneSymbol("ybtT");
	 a.setEcNumbers("3.1.2.-");
	 a.setRoleIds("707");
	 a.setGoIds("GO:0016788,GO:0019290");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end