#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2717 THIS_HMM_HIT[TIGR01587] && THIS_HMM_HIT[TIGR01596]
rule "2717|CRISPR-associated fused helicase/endonuclease Cas3 by TIGR01587/TIGR01596"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01587' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01596' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2717");
	a.setCommonName("CRISPR-associated helicase/endonuclease Cas3");
	a.setEcNumbers("3.1.-.-");
	a.setGeneSymbol("cas3");
	a.setGoIds("GO:0004521,GO:0043571,GO:0004386");
	a.setRoleIds("708");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end