#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2471 DEFAULT_METHOD[RF|YP_001781439.1]
rule "putative stage III sporulation protein AH"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001781439.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2471");
	 a.setGoIds("GO:0003674,GO:0030436");
	 a.setRoleIds("705");
	 a.setCommonName("putative stage III sporulation protein AH");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end