#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2523 DEFAULT_METHOD[GB|AAK80148.1]
rule "2523|cytidylyltransferase after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAK80148.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2523");
	a.setCommonName("cytidylyltransferase");
	a.setEcNumbers("2.7.7.-");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0009103,GO:0016779");
	a.setRoleIds("90");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end