#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2467 DEFAULT_METHOD[RF|YP_001781411.1]
rule "2467|pyrimidine-nucleoside phosphorylase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781411.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2467");
	a.setCommonName("pyrimidine-nucleoside phosphorylase");
	a.setEcNumbers("2.4.2.2");
	a.setGoIds("GO:0016154,GO:0043097");
	a.setRoleIds("127");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end