#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2687 THIS_BLAST_HIT[GB|BAB32408.1, 400, 95, 92, 85, 5, 0] && THIS_HMM_HIT[PF02909] && THIS_HMM_HIT[PF00440]
rule "2687|virginiamycin S resistance transcriptional regulator VarR"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|BAB32408.1', 
				bitScore >= 400, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 85, 
				hitQueryLengthRatio <= 5 )
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF02909' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='PF00440' )
	gene1 : Feature( featureId == blast_hit1.queryId, featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2687");
	a.setCommonName("virginiamycin S resistance transcriptional regulator VarR");
	a.setGeneSymbol("varR");
	a.setGoIds("GO:0051606,GO:0003700,GO:0006355,GO:0043565");
	a.setRoleIds("261,94");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end