#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2413 (THIS_GO_TERM[GO:0030435] || THIS_GO_TERM[GO:0043936]) && GEN_PROP[GenProp0610, 0.6] && GEN_STATE[GenProp0078, Firmicutes]
rule "2413|upgade GO process for endospore formers from sporulation to endospore"
no-loop true
when
	(
		(
			annot : Annotation( goIds contains 'GO:0030435' )
			gene1 : Feature( assignedAnnotation == annot )
		)
		or
		(
			annot1 : Annotation( goIds contains 'GO:0043936' )
			gene1 : Feature( assignedAnnotation == annot1 )
		)
		genprop1 : GenomeProperty( this['id'] == 'GenProp0610', this['value'] >= 0.6 )
		txn1 : Taxon( parentNames contains 'Firmicutes' )
		gene1 : Feature( taxon == txn1, properties contains genprop1 )
	)


then
	Annotation a = new Annotation("2413");
	a.addGoIds("GO:0034301");
	a.setConfidence(99);
	a.setSpecificity(SpecificityType.INITIALIZE);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end