#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2677 THIS_BLAST_HIT[GB|CAD66853.1, 160, 95, 92, 50, 3, 0]
rule "2677|GTP cyclohydrolase I"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|CAD66853.1', 
				bitScore >= 160, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 50, 
				hitQueryLengthRatio <= 3 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2677");
	a.setCommonName("GTP cyclohydrolase I");
	a.setEcNumbers("3.5.4.16");
	a.setGeneSymbol("folE");
	a.setGoIds("GO:0003934,GO:0046654");
	a.setRoleIds("78");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end