#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2588 THIS_HMM_HIT[TIGR01344] && THIS_HMM_HIT[TIGR01346]
rule "malate synthase A/isocitrate lyase"
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01344' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01346' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2588");
	 a.setGoIds("GO:0004474,GO:0004451,GO:0006099");
	 a.setEcNumbers("2.3.3.9 4.1.3.1");
	 a.setCommonName("malate synthase A/isocitrate lyase");
	 a.setRoleIds("120");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end