#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2392 THIS_HMM_HIT[TIGR00476] && GEN_PROP[GenProp0016, 0.45]
rule "selenide, water dikinase: GO terms for selenocysteine"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00476' )
	 and
	 genprop1 : GenomeProperty( this['id'] == 'GenProp0016', this['value'] >= 0.45 )
gene1 : Feature( properties contains genprop1, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2392");
	 a.addGoIds("GO:0004756,GO:0016260");
	 a.addRoleIds("137");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end