#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2613 THIS_HMM_HIT[TIGR00884] && THIS_HMM_HIT[TIGR00888]
rule "GMP synthase (glutamine-hydrolyzing)"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00884' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR00888' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2613");
	 a.setGoIds("GO:0003922,GO:0009152");
	 a.setEcNumbers("6.3.5.2");
	 a.setRoleIds("125");
	 a.setCommonName("GMP synthase (glutamine-hydrolyzing)");
	 a.setGeneSymbol("guaA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end