#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2572 DEFAULT_METHOD[RF|ZP_03568276.1]
rule "2572|sortase variant motif VPYMG cell wall-anchored repeat protein"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|ZP_03568276.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2572");
	a.setCommonName("sortase variant motif VPYMG cell wall-anchored repeat protein");
	a.addGoIds("GO:0005618");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end