#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2611 THIS_HMM_HIT[TIGR01361] && THIS_HMM_HIT[TIGR01801]
rule "chorismate mutase/phospho-2-dehydro-3-deoxyheptonate aldolase"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01361' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01801' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2611");
	 a.setGoIds("GO:0003849,GO:0009423,GO:0004106");
	 a.setEcNumbers("5.4.99.5 2.5.1.54");
	 a.setRoleIds("70");
	 a.setCommonName("chorismate mutase/phospho-2-dehydro-3-deoxyheptonate aldolase");
	 a.setGeneSymbol("aroAF");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end