#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2657 THIS_BLAST_HIT[GB|ABB67999.1, 400, 96, 96, 80, 3, 0]
rule "2657|glutamate-based acid resistance transcriptional regulator GadX"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABB67999.1', 
				bitScore >= 400, 
				hitPercentLength >= 96, 
				queryPercentLength >= 96, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 3 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2657");
	a.setCommonName("glutamate-dependent acid resistance transcriptional regulator GadX");
	a.setGeneSymbol("gadX");
	a.addGoIds("GO:0005737,GO:0016563,GO:0010447,GO:0006355");
	a.addRoleIds("261");
	a.setConfidence(98);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end