#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2466 DEFAULT_METHOD[RF|YP_001781407.1]
rule "2466|serine-type D-Ala-D-Ala carboxypeptidase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781407.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2466");
	a.setCommonName("serine-type D-Ala-D-Ala carboxypeptidase");
	a.setEcNumbers("3.4.16.4");
	a.setGeneSymbol("dacF");
	a.setGoIds("GO:0009002,GO:0009252");
	a.setRoleIds("89");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end