#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2539 DEFAULT_METHOD[SP|P27346]
rule "glutamate dehydrogenase, NAD-specific after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P27346', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2539");
	 a.setGoIds("GO:0004352,GO:0006538");
	 a.setEcNumbers("1.4.1.2");
	 a.setRoleIds("109");
	 a.setCommonName("glutamate dehydrogenase, NAD-specific");
	 a.setGeneSymbol("gluD");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end