#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2523 DEFAULT_METHOD[GB|AAK80148.1]
rule "cytidylyltransferase after MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|AAK80148.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2523");
	 a.setGoIds("GO:0009103,GO:0016779");
	 a.setEcNumbers("2.7.7.-");
	 a.setRoleIds("90");
	 a.setCommonName("cytidylyltransferase");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end