#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2627 THIS_BLAST_HIT[RF|YP_021914.2, 251, 85, 85, 50, 10, 0] && THIS_HMM_HIT[PF05738] && THIS_HMM_HIT[TIGR01167]
rule "2627|LPXTG-anchored collagen adhesion protein"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_021914.2', 
				bitScore >= 251, 
				hitPercentLength >= 85, 
				queryPercentLength >= 85, 
				percentIdentity >= 50, 
				hitQueryLengthRatio <= 10 )
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF05738' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01167' )
	gene1 : Feature( featureId == blast_hit1.queryId, featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2627");
	a.setCommonName("LPXTG-anchored collagen adhesion protein");
	a.setGoIds("GO:0031589,GO:0005518");
	a.setRoleIds("88");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end