#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2567 DEFAULT_METHOD[SP|P0ACJ0]
rule "leucine-responsive regulatory protein"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P0ACJ0', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2567");
	 a.setGoIds("GO:0003700,GO:0006355,GO:0015820");
	 a.setRoleIds("261");
	 a.setCommonName("leucine-responsive regulatory protein");
	 a.setGeneSymbol("lrp");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end