#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2333 THIS_HMM_HIT[TIGR01050] && GEN_STATE[GenProp0006,Bacteria]
rule "50S ribosomal protein S19 by HMM in BACTERIA"
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01050' )
	 and
	 txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2333");
	 a.setGeneSymbol("rpsS");
	 a.setRoleIds("158");
	 a.setGoIds("GO:0003735,GO:0006412,GO:0022627");
	 a.setCommonName("30S ribosomal protein S19");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end