#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2517 THIS_BLAST_HIT[GB|CAC98662.1, 1200, 90, 90, 80, 5, 0]
rule "2517|accessory Sec system translocase SecA2"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|CAC98662.1', 
				bitScore >= 1200, 
				hitPercentLength >= 90, 
				queryPercentLength >= 90, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2517");
	a.setCommonName("accessory Sec system translocase SecA2");
	a.setGeneSymbol("secA2");
	a.setGoIds("GO:0009306,GO:0015450");
	a.setRoleIds("97");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end