#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2594 DEFAULT_METHOD[GB|CAL84267.1]
rule "flagellar glycosylation island protein, CBO2706 family"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|CAL84267.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2594");
	 a.setGoIds("GO:0003674,GO:0008150");
	 a.setRoleIds("91");
	 a.setCommonName("flagellar glycosylation island protein, CBO2706 family");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end