#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2557 DEFAULT_METHOD[SP|P23847]
rule "dipeptide ABC transporter, periplasmic dipeptide-binding protein DppA"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P23847', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2557");
	 a.setGoIds("GO:0015440,GO:0030288,GO:0042277,GO:0042938");
	 a.setRoleIds("142");
	 a.setCommonName("dipeptide ABC transporter, periplasmic dipeptide-binding protein DppA");
	 a.setGeneSymbol("dppA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end