#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2421 DEFAULT_METHOD[GB|ABK62540.1]
rule "precorrin-8X methylmutase"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABK62540.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2421");
	 a.setGoIds("GO:0009236,GO:0016993");
	 a.setEcNumbers("5.4.1.2");
	 a.setCommonName("precorrin-8X methylmutase");
	 a.setRoleIds("79");
	 a.setGeneSymbol("cobH");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end