#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2714 THIS_BLAST_HIT[GB|AAG03576.1, 350, 90, 90, 60, 5, 0]
rule "sulfate ester ABC transporter, periplasmic sulfate ester-binding protein AtsR"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|AAG03576.1', 
			bitScore >= 350,
			hitPercentLength >= 90,
			queryPercentLength >= 90,  
			percentIdentity >= 60,
			hitQueryLengthRatio <= 5 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2714");
	 a.setRoleIds("147");
	 a.setCommonName("sulfate ester ABC transporter, periplasmic sulfate ester-binding protein AtsR");
	 a.setGeneSymbol("atsR");
	 a.addGoIds("GO:0030288,GO:0055052,GO:0042626:contributes_to");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end