#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2524 DEFAULT_METHOD[GB|ACA56757.1]
rule "D-proline reductase, PrdA proprotein"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA56757.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2524");
	 a.setGoIds("GO:0006562,GO:0050002");
	 a.setEcNumbers("1.21.4.1");
	 a.setRoleIds("109");
	 a.setCommonName("D-proline reductase, PrdA proprotein");
	 a.setGeneSymbol("prdA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end