#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2524 DEFAULT_METHOD[GB|ACA56757.1]
rule "2524|D-proline reductase, PrdA proprotein"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA56757.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2524");
	a.setCommonName("D-proline reductase, PrdA proprotein");
	a.setEcNumbers("1.21.4.1");
	a.setGeneSymbol("prdA");
	a.setGoIds("GO:0006562,GO:0050002");
	a.setRoleIds("109");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end