#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2310 THIS_HMM_HIT[TIGR01171] && GEN_STATE[GenProp0006,Bacteria]
rule "2310|50S ribosomal protein L2 by HMM in BACTERIA"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01171' )
	txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2310");
	a.setCommonName("50S ribosomal protein L2");
	a.setEcNumbers(" ");
	a.setGeneSymbol("rplB");
	a.setGoIds("GO:0003735,GO:0006412,GO:0022625");
	a.setRoleIds("158");
	a.setConfidence();
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end