#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2475 DEFAULT_METHOD[RF|YP_001781500.1]
rule "2475|aldehyde ferredoxin oxidoreductase, tungsten-containing"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781500.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2475");
	a.setCommonName("aldehyde ferredoxin oxidoreductase, tungsten-containing");
	a.setGoIds("GO:0006081,GO:0033726");
	a.setRoleIds("184");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end