#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2545 THIS_BLAST_HIT[RF|YP_016859.1, 70, 92, 92, 50, 5, 0] %% NEAR_BLAST_HIT[100, RF|YP_893153.1, 100, 95, 92, 50, 5, 0]
rule "addiction module antitoxin component PemI"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_016859.1', 
			bitScore >= 70,
			hitPercentLength >= 92,
			queryPercentLength >= 92,  
			percentIdentity >= 50,
			hitQueryLengthRatio <= 5 
		)
	 blast_hit2 : BlastHit( program=='blastp', hitId=='RF|YP_893153.1', 
			bitScore >= 100,
			hitPercentLength >= 95,
			queryPercentLength >= 92,  
			percentIdentity >= 50,
			hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit2.queryId, featureId == blast_hit1.queryId )
	gene2 : Feature( eval(gene2.isWithin(gene1, 100)) )
	
 then
	 Annotation a = new Annotation("2545");
	 a.setGoIds("GO:0003700,GO:0006355,GO:0015643");
	 a.setRoleIds("149");
	 a.setCommonName("addiction module antitoxin component PemI");
	 a.setGeneSymbol("pemI");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end