#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2410 DEFAULT_METHOD[RF|YP_001781221.1]
rule "2410|putative lantibiotic biosynthesis regulatory protein after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781221.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2410");
	a.setCommonName("putative lantibiotic biosynthesis regulatory protein");
	a.setEcNumbers(" ");
	a.setGoIds("GO:0000156,GO:0000160,GO:0006355,GO:0030651");
	a.setRoleIds("94,261,699");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end