#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2339 DEFAULT_METHOD[SP|O07623]
rule "subtilosin-A by default method"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|O07623', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2339");
	 a.setCommonName("subtilosin-A");
	 a.setGeneSymbol("sboA");
	 a.setRoleIds("94");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end