#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2560 DEFAULT_METHOD[GB|ACA56606.1]
rule "chemotaxis protein MotB after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA56606.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2560");
	 a.setGoIds("GO:0003774,GO:0006935");
	 a.setRoleIds("188");
	 a.setCommonName("chemotaxis protein MotB");
	 a.setGeneSymbol("motB");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end