#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2442 DEFAULT_METHOD[GB|ABS42103.1]
rule "sulfite reductase, subunit C after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABS42103.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2442");
	 a.setEcNumbers("1.8.-.-");
	 a.setGoIds("GO:0006790,GO:0016002");
	 a.setRoleIds("106");
	 a.setCommonName("sulfite reductase, subunit C");
	 a.setGeneSymbol("asrC");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end