#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2449 DEFAULT_METHOD[GB|EDK35753.1]
rule "spore maturation protein B after MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|EDK35753.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2449");
	 a.setGoIds("GO:0016021,GO:0034301");
	 a.setRoleIds("705");
	 a.setCommonName("spore maturation protein B");
	 a.setGeneSymbol("spmB");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end