#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2275 DEFAULT_METHOD[GB|AAB82564.1]
rule "methanesulfonate sulfonatase MsuD"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|AAB82564.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2275");
	 a.setCommonName("methanesulfonate sulfonatase MsuD");
	 a.setGeneSymbol("msuD");
	 a.setEcNumbers("1.14.14.5");
	 a.setRoleIds("106");
	 a.setGoIds("GO:0008726,GO:0019694");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end