#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2714 THIS_BLAST_HIT[GB|AAG03576.1, 350, 90, 90, 60, 5, 0]
rule "2714|sulfate ester ABC transporter, periplasmic sulfate ester-binding protein AtsR"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAG03576.1', 
				bitScore >= 350, 
				hitPercentLength >= 90, 
				queryPercentLength >= 90, 
				percentIdentity >= 60, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2714");
	a.setCommonName("sulfate ester ABC transporter, periplasmic sulfate ester-binding protein AtsR");
	a.setGeneSymbol("atsR");
	a.addGoIds("GO:0030288,GO:0055052,GO:0042626");
	a.setRoleIds("147");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end