#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2480 DEFAULT_METHOD[SP|A0Q074|]
rule "2480|pyrimidine operon regulatory protein/uracil phosphoribosyltransferase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|A0Q074|', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2480");
	a.setCommonName("pyrimidine operon regulatory protein/uracil phosphoribosyltransferase");
	a.setEcNumbers("2.4.2.9");
	a.setGeneSymbol("pyrR");
	a.setGoIds("GO:0003700,GO:0004845,GO:0006355,GO:0009220");
	a.setRoleIds("126,261");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end