#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2511 DEFAULT_METHOD[GB|ACA44514.1]
rule "2511|ATP-dependent RNA helicase DbpA after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA44514.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2511");
	a.setCommonName("ATP-dependent RNA helicase DbpA");
	a.setEcNumbers("3.6.1.-");
	a.setGeneSymbol("dbpA");
	a.setGoIds("GO:0003723,GO:0004004,GO:0006139,GO:0007046,GO:0008186,GO:0016070,GO:0016818");
	a.setRoleIds("133");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end