#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2483 DEFAULT_METHOD[GB|AAK80070.1]
rule "uracil permease"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|AAK80070.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2483");
	 a.setGoIds("GO:0015505,GO:0015857,GO:0016021");
	 a.setRoleIds("146");
	 a.setCommonName("uracil permease");
	 a.setGeneSymbol("pyrP");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end