#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2570 DEFAULT_METHOD[SP|P00195]
rule "ferredoxin, 4Fe-4S"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P00195', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2570");
	 a.setGoIds("GO:0005506,GO:0006118,GO:0009055,GO:0055114");
	 a.setRoleIds("112");
	 a.setCommonName("ferredoxin, 4Fe-4S");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end