#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2669 THIS_BLAST_HIT[GB|AAK46051.1, 900, 92, 92, 80, 5, 0]
rule "2669|nitrate reductase-related protein NarX"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAK46051.1', 
				bitScore >= 900, 
				hitPercentLength >= 92, 
				queryPercentLength >= 92, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2669");
	a.setCommonName("nitrate reductase-related protein NarX");
	a.setGeneSymbol("narX");
	a.setRoleIds("157");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end