#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2543 DEFAULT_METHOD[RF|YP_001781881.1]
rule "2543|choloylglycine hydrolase family protein"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781881.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2543");
	a.setCommonName("choloylglycine hydrolase family protein");
	a.setEcNumbers(" ");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0008152,GO:0016811");
	a.setRoleIds("703");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end