#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2162 THIS_BLAST_HIT[GB|CAA73127.1, 4000, 95, 92, 80, 5, 1]
rule "2162|yersiniabactin biosynthesis enzyme HMWP1, BLASTP"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|CAA73127.1', 
				bitScore >= 4000, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2162");
	a.setCommonName("yersiniabactin synthetase, HMWP1 component");
	a.setGeneSymbol("irp1");
	a.addGoIds("GO:0019290,GO:0003824");
	a.setRoleIds("706");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end