#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2459 DEFAULT_METHOD[GB|ACA57525.1]
rule "bontoxilysin A after MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA57525.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2459");
	 a.setGoIds("GO:0009405,GO:0033264");
	 a.setEcNumbers("3.4.24.69");
	 a.setCommonName("bontoxilysin A");
	 a.setRoleIds("94,187");
	 a.setGeneSymbol("botA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end