#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2530 THIS_BLAST_HIT[GB|ABK84171.1, 1200, 90, 90, 80, 5, 0]
rule "putative accessory secretory protein SecA2"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABK84171.1', 
			bitScore >= 1200,
			hitPercentLength >= 90,
			queryPercentLength >= 90,  
			percentIdentity >= 80,
			hitQueryLengthRatio <= 5 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2530");
	 a.setGoIds("GO:0009306,GO:0015450");
	 a.setCommonName("putative accessory secretory protein SecA2");
	 a.setRoleIds("97");
	 a.setGeneSymbol("secA2");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end