#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2280 THIS_HMM_HIT[PF00276] && GEN_STATE[GenProp0006,Bacteria]
rule "L23 by HMM in Bacteria"
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF00276' )
	 and
	 txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2280");
	 a.setGoIds("GO:0003735,GO:0006412,GO:0022625,GO:0019843");
	 a.setCommonName("50S ribosomal protein L23");
	 a.setRoleIds("158");
	 a.setGeneSymbol("rplW");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end