#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2679 THIS_BLAST_HIT[GB|BAA85309.1, 290, 95, 92, 66, 3, 0]
rule "2679|copper resistance response regulator CopR"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|BAA85309.1', 
				bitScore >= 290, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 66, 
				hitQueryLengthRatio <= 3 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2679");
	a.setCommonName("copper resistance response regulator CopR");
	a.setGeneSymbol("copR");
	a.setGoIds("GO:0000156:,,GO:0000160:,,GO:0003700:,,GO:0006355:,,GO:0046688");
	a.setRoleIds("96,261,263,699");
	a.setConfidence(98);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end