#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2433 DEFAULT_METHOD[RF|YP_001779931.1]
rule "maltose-6'-phosphate glucosidase after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001779931.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2433");
	 a.setGoIds("GO:0005975,GO:0050081");
	 a.setEcNumbers("3.2.1.122");
	 a.setRoleIds("105");
	 a.setCommonName("maltose-6'-phosphate glucosidase");
	 a.setGeneSymbol("glvA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end