#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2614 THIS_HMM_HIT[TIGR00398] && GENOME_HMM_HIT[TIGR00399] && !THIS_HMM_HIT[TIGR00399]
rule "2614|methionyl-tRNA synthetase, alpha subunit"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00398' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR00399' )
	not HmmHit( program=='hmm', hitId=='TIGR00399', queryId == gene1.featureId )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2614");
	a.setCommonName("methionyl-tRNA synthetase, alpha subunit");
	a.setEcNumbers("6.1.1.10");
	a.setGeneSymbol("metS");
	a.setGoIds("GO:0004825,GO:0006431");
	a.setRoleIds("137");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end