#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2645 THIS_BLAST_HIT[GB|AAQ16631.1, 1250, 95, 92, 85, 5, 0] || (THIS_BLAST_HIT[GB|AAQ16631.1, 900, 95, 92, 60, 5, 1] || NEAR_HMM_HIT[500,TIGR00905])
rule "2645|lysine decarboxylase CadA"
no-loop true
when
	(
		blast_hit : BlastHit( program=='blastp', 
				hitId=='GB|AAQ16631.1', 
				bitScore >= 1250, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 85, 
				hitQueryLengthRatio <= 5 )
		gene1 : Feature( featureId == blast_hit.queryId )
	)
	or
	(
		(
			(
				blast_hit : BlastHit( program=='blastp', 
				hitId=='GB|AAQ16631.1', 
				bitScore >= 900, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 60, 
				hitQueryLengthRatio <= 5 )
				gene1 : Feature( featureId == blast_hit.queryId )
			)
			or
			(
				hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00905' )
				gene1 : Feature( featureId == hmm_hit1.queryId )
				gene2 : Feature( eval(gene2.isWithin(gene1, 500)) )
			)
		)
	)


then
	Annotation a = new Annotation("2645");
	a.setCommonName("lysine decarboxylase CadA");
	a.setEcNumbers("4.1.1.18");
	a.setGeneSymbol("cadA");
	a.addGoIds("GO:0006885,GO:0008923,GO:0046440");
	a.setRoleIds("149");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end