#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2476 DEFAULT_METHOD[SP|Q00758  ]
rule "2476|stage V sporulation protein B"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|Q00758', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2476");
	a.setCommonName("stage V sporulation protein B");
	a.setEcNumbers(" ");
	a.setGeneSymbol("spoVB");
	a.setGoIds("GO:0003674,GO:0016021,GO:0030436");
	a.setRoleIds("705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end