#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2672 THIS_HMM_HIT[TIGR00091] && THIS_HMM_HIT[TIGR03534]
rule "protein-(glutamine-N5) methyltransferase/tRNA (guanine-N(7)-)-methyltransferase"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00091' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR03534' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2672");
	 a.setGoIds("GO:0008276,GO:0008176,GO:0018364,GO:0008757,GO:0006400");
	 a.setEcNumbers("2.1.1.- 2.1.1.33");
	 a.setCommonName("protein-(glutamine-N5) methyltransferase/tRNA (guanine-N(7)-)-methyltransferase");
	 a.setRoleIds("140,168");
	 a.setGeneSymbol("prmC/trmB");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end