#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2436 THIS_HMM_HIT[TIGR00121] && !THIS_HMM_HIT[PF08279] && !THIS_HMM_HIT[TIGR00122]
rule "2436|biotin-[acetyl-CoA-carboxylase] ligase (NOT with repressor domain)"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00121' )
	not HmmHit( program=='hmm', hitId=='PF08279', queryId == gene1.featureId )
	not HmmHit( program=='hmm', hitId=='TIGR00122', queryId == gene1.featureId )
	gene1 : Feature( featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2436");
	a.setCommonName("biotin-[acetyl-CoA-carboxylase] ligase");
	a.setEcNumbers("6.3.4.15");
	a.setGeneSymbol("bpl");
	a.setGoIds("GO:0004077,GO:0009102");
	a.setRoleIds("77,140");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end