#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2619 THIS_HMM_HIT[TIGR00635] && THIS_HMM_HIT[TIGR00084]
rule "Holliday junction DNA helicase RuvA/RuvB"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00635' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR00084' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2619");
	 a.setGoIds("GO:0006310,GO:0009378,GO:0009379");
	 a.setEcNumbers("3.6.1.-");
	 a.setCommonName("Holliday junction DNA helicase RuvA/RuvB");
	 a.setRoleIds("132");
	 a.setGeneSymbol("ruvAB");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end