#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2512 DEFAULT_METHOD[SP|P45693]
rule "stage V sporulation protein S"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P45693', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2512");
	 a.setGoIds("GO:0000917,GO:0030435");
	 a.setRoleIds("705");
	 a.setCommonName("stage V sporulation protein S");
	 a.setGeneSymbol("spoVS");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end