#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2423 DEFAULT_METHOD[RF|YP_001386738.1] && GEN_STATE[GenProp0079, Clostridia]
rule "2423|bontoxilysin after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001386738.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	txn1 : Taxon( parentNames contains 'Clostridia' )
	gene1 : Feature( taxon == txn1, featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2423");
	a.setCommonName("bontoxilysin");
	a.setEcNumbers("3.4.24.69");
	a.setGeneSymbol("botA");
	a.setGoIds("GO:0009405,GO:0033264");
	a.setRoleIds("94,187");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end