#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2535 DEFAULT_METHOD[GB|ABS40983.1]
rule "putative tail length tape measure protein after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABS40983.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2535");
	 a.setGoIds("GO:0005198,GO:0019038,GO:0019068");
	 a.setRoleIds("152");
	 a.setCommonName("putative tail length tape measure protein");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end