#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2576 DEFAULT_METHOD[GB|ABS34100.1]
rule "flagellar glycosylation island glycosyltransferase, CBO2703 family"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABS34100.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2576");
	 a.setEcNumbers("2.4.1.-");
	 a.setRoleIds("91");
	 a.setCommonName("flagellar glycosylation island glycosyltransferase, CBO2703 family");
	 a.addGoIds("GO:0000271,GO:0016757");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end