#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2421 DEFAULT_METHOD[GB|ABK62540.1]
rule "2421|precorrin-8X methylmutase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABK62540.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2421");
	a.setCommonName("precorrin-8X methylmutase");
	a.setEcNumbers("5.4.1.2");
	a.setGeneSymbol("cobH");
	a.setGoIds("GO:0009236,GO:0016993");
	a.setRoleIds("79");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end