#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2594 DEFAULT_METHOD[GB|CAL84267.1]
rule "2594|flagellar glycosylation island protein, CBO2706 family"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|CAL84267.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2594");
	a.setCommonName("flagellar glycosylation island protein, CBO2706 family");
	a.setEcNumbers(" ");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0003674,GO:0008150");
	a.setRoleIds("91");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end