#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2693 THIS_BLAST_HIT[RF|YP_055749.1, 700, 95, 92, 80, 5, 0]
rule "polyunsaturated fatty acid isomerase, conjugated linoleic acid-producing by strong BLAST"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_055749.1', 
			bitScore >= 700,
			hitPercentLength >= 95,
			queryPercentLength >= 92,  
			percentIdentity >= 80,
			hitQueryLengthRatio <= 5 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2693");
	 a.setRoleIds("176");
	 a.setCommonName("polyunsaturated fatty acid isomerase, conjugated linoleic acid-producing");
	 a.setGoIds("GO:0016860,GO:0006631,GO:0050660");
	 a.setEcNumbers("5.3.-.-");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end