#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2601 THIS_HMM_HIT[TIGR02365] && NEAR_HMM_HIT[1000,TIGR02364] && !THIS_HMM_HIT[TIGR02363]
rule "PTS-dependent dihydroxyacetone kinase, DhaL subunit"
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02365' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02364' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	gene2 : Feature( eval(gene2.isWithin(gene1, 1000)) )
	not HmmHit( program=='hmm', hitId=='TIGR02363', queryId == gene2.featureId )
	
 then
	 Annotation a = new Annotation("2601");
	 a.setGoIds("GO:0006071,GO:0016772");
	 a.setEcNumbers("2.7.-.-");
	 a.setRoleIds("184");
	 a.setCommonName("PTS-dependent dihydroxyacetone kinase, DhaL subunit");
	 a.setGeneSymbol("dhaL");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end