#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2558 DEFAULT_METHOD[SP|P0AEF8]
rule "dipeptide ABC transporter, permease protein DppB"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P0AEF8', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2558");
	 a.setGeneSymbol("dppB");
	 a.setGoIds("GO:0005887,GO:0015440,GO:0042936,GO:0042938");
	 a.setRoleIds("142");
	 a.setCommonName("dipeptide ABC transporter, permease protein DppB");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end