#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2460 DEFAULT_METHOD[RF|YP_001781265.1]
rule "putative acetoin catabolism protein X"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001781265.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2460");
	 a.setGoIds("GO:0003674,GO:0045150");
	 a.setRoleIds("110,114");
	 a.setCommonName("putative acetoin catabolism protein X");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end