#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2599 DEFAULT_METHOD[GB|CAL84274.1]
rule "2599|flagellar glycosylation island methyltransferase, CBO2713 family"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|CAL84274.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2599");
	a.setCommonName("flagellar glycosylation island methyltransferase, CBO2713 family");
	a.setEcNumbers(" ");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0005575,GO:0008150,GO:0008168");
	a.setRoleIds("91");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end