#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2556 DEFAULT_METHOD[SP|O86447]
rule "putative coniferyl aldehyde dehydrogenase"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|O86447', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2556");
	 a.setGoIds("GO:0006113,GO:0050269");
	 a.setEcNumbers("1.2.1.68");
	 a.setRoleIds("114");
	 a.setCommonName("putative coniferyl aldehyde dehydrogenase");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end