#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2474 DEFAULT_METHOD[GB|BAA74792.1]
rule "nitrate reductase, iron-sulfur subunit"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|BAA74792.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2474");
	 a.setGoIds("GO:0006118,GO:0008942,GO:0009055");
	 a.setRoleIds("160");
	 a.setCommonName("nitrate reductase, iron-sulfur subunit");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end