#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2617 THIS_HMM_HIT[TIGR01115] && THIS_HMM_HIT[TIGR01157]
rule "photosynthetic reaction center, L/M subunits"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01115' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01157' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2617");
	 a.setGoIds("GO:0005488,GO:0009521,GO:0019684");
	 a.setCommonName("photosynthetic reaction center, L/M subunits");
	 a.setRoleIds("112,164");
	 a.setGeneSymbol("pufLM");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end