#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2692 THIS_BLAST_HIT[RF|NP_247226.1, 275, 95, 92, 55300, 3, 0]
rule "phosphosulfolactate synthase"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|NP_247226.1', 
			bitScore >= 275,
			hitPercentLength >= 95,
			queryPercentLength >= 92,  
			percentIdentity >= 55300,
			hitQueryLengthRatio <= 3 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2692");
	 a.setGoIds("GO:0043817,GO:0019295");
	 a.setEcNumbers("4.4.1.19");
	 a.setRoleIds("76,159");
	 a.setCommonName("phosphosulfolactate synthase");
	 a.setGeneSymbol("comA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end