#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2689 THIS_HMM_HIT[TIGR03845] && THIS_HMM_HIT[TIGR03846]
rule "2689|sulfopyruvate decarboxylase"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR03845' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR03846' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2689");
	a.setCommonName("sulfopyruvate decarboxylase ComDE");
	a.setEcNumbers("4.1.1.79");
	a.setGeneSymbol("comDE");
	a.setGoIds("GO:0050545,GO:0019295");
	a.setRoleIds("76,159");
	a.setConfidence(98);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end