#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2620 THIS_HMM_HIT[TIGR02400] && THIS_HMM_HIT[TIGR00685]
rule "2620|alpha,alpha-trehalose-phosphate synthase (UDP-forming)/trehalose-phosphatase"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02400' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR00685' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2620");
	a.setCommonName("alpha,alpha-trehalose-phosphate synthase (UDP-forming)/trehalose-phosphatase");
	a.setEcNumbers("2.4.1.15 3.1.3.12");
	a.setGeneSymbol("otsAB");
	a.setGoIds("GO:0003825,GO:0004805,GO:0005992");
	a.setRoleIds("149");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end