#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2617 THIS_HMM_HIT[TIGR01115] && THIS_HMM_HIT[TIGR01157]
rule "2617|photosynthetic reaction center, L/M subunits"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01115' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01157' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2617");
	a.setCommonName("photosynthetic reaction center, L/M subunits");
	a.setEcNumbers(" ");
	a.setGeneSymbol("pufLM");
	a.setGoIds("GO:0005488,GO:0009521,GO:0019684");
	a.setRoleIds("112,164");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end