#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2503 DEFAULT_METHOD[GB|ACA55393.1]
rule "2503|protein-glutamine gamma-glutamyltransferase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA55393.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2503");
	a.setCommonName("protein-glutamine gamma-glutamyltransferase");
	a.setEcNumbers("2.3.2.13");
	a.setGeneSymbol("tgl");
	a.setGoIds("GO:0003810,GO:0030436");
	a.setRoleIds("705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end