#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2689 THIS_HMM_HIT[TIGR03845] && THIS_HMM_HIT[TIGR03846]
rule "sulfopyruvate decarboxylase"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR03845' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR03846' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2689");
	 a.setGoIds("GO:0050545,GO:0019295");
	 a.setEcNumbers("4.1.1.79");
	 a.setRoleIds("76,159");
	 a.setCommonName("sulfopyruvate decarboxylase ComDE");
	 a.setGeneSymbol("comDE");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end