#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2713 THIS_BLAST_HIT[OMNI|NTL02MT00710, 375, 95, 91, 60, 4, 0]
rule "cysteine-type sulfatase aerobic maturase by BLAST"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='OMNI|NTL02MT00710', 
			bitScore >= 375,
			hitPercentLength >= 95,
			queryPercentLength >= 91,  
			percentIdentity >= 60,
			hitQueryLengthRatio <= 4 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2713");
	 a.setGoIds("GO:0018198,GO:0018307");
	 a.setEcNumbers("1.-.-.-");
	 a.setRoleIds("140");
	 a.setCommonName("cysteine-type sulfatase aerobic maturase");
	 a.setGeneSymbol("fge");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end