#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2547 DEFAULT_METHOD[RF|YP_001783178.1]
rule "putative peptidyl-prolyl cis-trans isomerase"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001783178.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2547");
	 a.setGoIds("GO:0003755,GO:0006457");
	 a.setRoleIds("95");
	 a.setCommonName("putative peptidyl-prolyl cis-trans isomerase");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end