#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2473 DEFAULT_METHOD[RF|YP_001781474.1]
rule "fibronectin-binding protein"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001781474.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2473");
	 a.setGoIds("GO:0001968,GO:0007155");
	 a.setRoleIds("701");
	 a.setCommonName("fibronectin-binding protein");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end