#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2514 DEFAULT_METHOD[GB|ACA55601.1]
rule "aspartate aminotransferase after MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA55601.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2514");
	 a.setGoIds("GO:0004069,GO:0006532");
	 a.setEcNumbers("2.6.1.1");
	 a.setRoleIds("71");
	 a.setCommonName("aspartate aminotransferase");
	 a.setGeneSymbol("aspB");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end