#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2606 THIS_HMM_HIT[TIGR02386] && THIS_HMM_HIT[TIGR02013]
rule "2606|DNA-directed RNA polymerase, beta/beta' subunits"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02386' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02013' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2606");
	a.setCommonName("DNA-directed RNA polymerase, beta/beta' subunits");
	a.setEcNumbers("2.7.7.6");
	a.setGeneSymbol("rpoBC");
	a.setGoIds("GO:0000345,GO:0003899,GO:0006350");
	a.setRoleIds("132,135");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end