#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2502 DEFAULT_METHOD[RF|YP_001781624.1]
rule "2502|cytosine permease"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781624.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2502");
	a.setCommonName("cytosine permease");
	a.setEcNumbers(" ");
	a.setGeneSymbol("codB");
	a.setGoIds("GO:0015504,GO:0015856");
	a.setRoleIds("146");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end