#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2492 DEFAULT_METHOD[RF|YP_001781592.1]
rule "putative Xaa-Pro dipeptidase"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001781592.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2492");
	 a.setGoIds("GO:0004251,GO:0006508");
	 a.setEcNumbers("3.4.13.9");
	 a.setRoleIds("138");
	 a.setCommonName("putative Xaa-Pro dipeptidase");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end