#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2553 DEFAULT_METHOD[GB|AAF81073.1] && GEN_STATE[GenProp0078, Proteobacteria]
rule "putative transmembrane regulator PrtR"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|AAF81073.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	 and
	 txn1 : Taxon( parentNames contains 'Proteobacteria' )
	gene1 : Feature( taxon == txn1, featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2553");
	 a.setGoIds("GO:0030528,GO:0051090");
	 a.setRoleIds("263");
	 a.setCommonName("putative transmembrane regulator PrtR");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end