#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2284 THIS_HMM_HIT[PF00466] && GEN_STATE[GenProp0006,Bacteria]
rule "2284|50S ribosomal protein L10 by HMM in BACTERIA"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF00466' )
	txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2284");
	a.setCommonName("50S ribosomal protein L10");
	a.setEcNumbers(" ");
	a.setGeneSymbol("rplJ");
	a.setGoIds("GO:0003735,GO:0006412,GO:0022625,GO:0019843,GO:0005515,GO:0000900");
	a.setRoleIds("158");
	a.setConfidence();
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end