#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2496 DEFAULT_METHOD[GB|ACA40331.1]
rule "2496|major cold shock protein CspA"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA40331.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2496");
	a.setCommonName("major cold shock protein CspA");
	a.setEcNumbers(" ");
	a.setGeneSymbol("cspA");
	a.setGoIds("GO:0003677,GO:0006355,GO:0009409");
	a.setRoleIds("149");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end