#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2605 THIS_HMM_HIT[TIGR02425] && THIS_HMM_HIT[TIGR02427]
rule "2605|3-oxoadipate enol-lactone hydrolase/4-carboxymuconolactone decarboxylase"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02425' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02427' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2605");
	a.setCommonName("3-oxoadipate enol-lactone hydrolase/4-carboxymuconolactone decarboxylase");
	a.setEcNumbers("3.1.1.24 4.1.1.44");
	a.setGeneSymbol("pcaDC");
	a.setGoIds("GO:0042952,GO:0047570,GO:0047575");
	a.setRoleIds("184");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end