#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2165 THIS_BLAST_HIT[GB|CAL20547.1, 350, 95, 95, 80, 4, 1]
rule "2165|yersiniabactin biosynthesis thioesterase YbtT, BLASTP"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|CAL20547.1', 
				bitScore >= 350, 
				hitPercentLength >= 95, 
				queryPercentLength >= 95, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 4 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2165");
	a.setCommonName("yersiniabactin biosynthesis thioesterase YbtT");
	a.setEcNumbers("3.1.2.-");
	a.setGeneSymbol("ybtT");
	a.setGoIds("GO:0016788,GO:0019290");
	a.setRoleIds("707");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end