#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2548 DEFAULT_METHOD[GB|ABS42747.1]
rule "2548|triacylglycerol lipase after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABS42747.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2548");
	a.setCommonName("triacylglycerol lipase");
	a.setEcNumbers("3.1.1.3");
	a.setGeneSymbol("lipA");
	a.setGoIds("GO:0016042,GO:0016298");
	a.setRoleIds("177");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end