#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2386 THIS_BLAST_HIT[GB|AAN85822.1, 225, 90, 90, 80, 6, 0]
rule "2386|exosporium protein J"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAN85822.1', 
				bitScore >= 225, 
				hitPercentLength >= 90, 
				queryPercentLength >= 90, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 6 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2386");
	a.setCommonName("exosporium protein J");
	a.setGeneSymbol("exsJ");
	a.addGoIds("GO:0043592");
	a.setRoleIds("705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end