#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2497 DEFAULT_METHOD[RF|YP_001781621.1]
rule "2497|triacylglycerol lipase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781621.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2497");
	a.setCommonName("triacylglycerol lipase");
	a.setEcNumbers("3.1.1.3");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0016042,GO:0016298");
	a.setRoleIds("177");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end