#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2527 DEFAULT_METHOD[GB|EDK33034.1]
rule "2527|glutamine-dependent NAD(+) synthetase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|EDK33034.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2527");
	a.setCommonName("glutamine-dependent NAD(+) synthetase");
	a.setEcNumbers("6.3.5.1");
	a.setGeneSymbol("nadE");
	a.setGoIds("GO:0003952,GO:0009435");
	a.setRoleIds("163");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end