#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2555 DEFAULT_METHOD[SP|Q44532]
rule "putative ferredoxin--NADP reductase"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|Q44532', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2555");
	 a.setGoIds("GO:0004324,GO:0006118");
	 a.setEcNumbers("1.18.1.2");
	 a.setRoleIds("112");
	 a.setCommonName("putative ferredoxin--NADP reductase");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end