#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2602 THIS_HMM_HIT[TIGR02363] && NEAR_HMM_HIT[2000,TIGR02364] && !THIS_HMM_HIT[TIGR02365]
rule "2602|PTS-dependent dihydroxyacetone kinase, DhaK subunit"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02363' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02364' )
	not HmmHit( program=='hmm', hitId=='TIGR02365', queryId == gene2.featureId )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	gene2 : Feature( eval(gene2.isWithin(gene1, 2000)) )


then
	Annotation a = new Annotation("2602");
	a.setCommonName("PTS-dependent dihydroxyacetone kinase, DhaK subunit");
	a.setEcNumbers("2.7.-.-");
	a.setGeneSymbol("dhaK");
	a.setGoIds("GO:0006071,GO:0016772");
	a.setRoleIds("184");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end