#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2445 DEFAULT_METHOD[GB|ACA46415.1]
rule "proton/sodium-glutamate symporter after MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA46415.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2445");
	 a.setGoIds("GO:0015295,GO:0015813");
	 a.setRoleIds("142");
	 a.setCommonName("proton/sodium-glutamate symporter");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end