#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2427 DEFAULT_METHOD[RF|YP_001780854.1] && GEN_STATE[GenProp0078, Firmicutes]
rule "CotJB protein after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001780854.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	 and
	 txn1 : Taxon( parentNames contains 'Firmicutes' )
	gene1 : Feature( taxon == txn1, featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2427");
	 a.setGoIds("GO:0003674,GO:0034301");
	 a.setRoleIds("705");
	 a.setCommonName("CotJB protein");
	 a.setGeneSymbol("cotJB");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end