#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2536 DEFAULT_METHOD[SP|P19940]
rule "2536|RNA polymerase sigma-G factor"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|P19940', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2536");
	a.setCommonName("RNA polymerase sigma-G factor");
	a.setEcNumbers(" ");
	a.setGeneSymbol("sigG");
	a.setGoIds("GO:0006352,GO:0016987,GO:0042173");
	a.setRoleIds("165,705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end