#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2353 THIS_HMM_HIT[TIGR00054] && GEN_STATE[GenProp0081, Bacillaceae]
rule "RIP metalloprotease RasP"
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00054' )
	 and
	 txn1 : Taxon( parentNames contains 'Bacillaceae' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2353");
	 a.setCommonName("RIP metalloprotease RasP");
	 a.setGeneSymbol("rasP");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end