#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2317 THIS_HMM_HIT[TIGR01021] && GEN_STATE[GenProp0006,Bacteria]
rule "2317|ribosomal protein S5, rpsE by HMM in superkingdom BACTERIA"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01021' )
	txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2317");
	a.setCommonName("30S ribosomal protein S5");
	a.setEcNumbers(" ");
	a.setGeneSymbol("rpsE");
	a.setGoIds("GO:0003735,GO:0006412,GO:0022627");
	a.setRoleIds("158");
	a.setConfidence();
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end