#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2443 DEFAULT_METHOD[GB|ACA56469.1]
rule "transcriptional antiterminator, LicT after MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA56469.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2443");
	 a.setGoIds("GO:0006355,GO:0030401,GO:0032950");
	 a.setRoleIds("262");
	 a.setCommonName("transcriptional antiterminator, LicT");
	 a.setGeneSymbol("licT");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end