#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2163 THIS_BLAST_HIT[RF|NP_993003.1, 600, 95, 95, 80, 3, 1] || THIS_BLAST_HIT[GB|AAZ37347.1, 600, 95, 95, 80, 3, 1]
rule "2163|yersiniabactin biosynthesis salycil-AMP ligase YbtE/Irp5 from Y. pestis or P. syringae"
no-loop true
when
	(
		blast_hit : BlastHit( program=='blastp', 
				hitId=='RF|NP_993003.1', 
				bitScore >= 600, 
				hitPercentLength >= 95, 
				queryPercentLength >= 95, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 3 )
		gene1 : Feature( featureId == blast_hit.queryId )
	)
	or
	(
		blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAZ37347.1', 
				bitScore >= 600, 
				hitPercentLength >= 95, 
				queryPercentLength >= 95, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 3 )
		gene1 : Feature( featureId == blast_hit1.queryId )
	)


then
	Annotation a = new Annotation("2163");
	a.setCommonName("yersiniabactin biosynthesis salycil-AMP ligase YbtE/Irp5");
	a.setEcNumbers("2.7.7.-");
	a.setGeneSymbol("ybtE");
	a.setGoIds("GO:0016779,GO:0019290");
	a.addRoleIds("707");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end