#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2464 THIS_HMM_HIT[TIGR00476] && GENOME_HMM_HIT[TIGR03309]
rule "2464|selenide, water dikinase: GO terms for labile selenium system"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00476' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR03309' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2464");
	a.addGoIds("GO:0070504");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end