#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2354 THIS_HMM_HIT[TIGR00195] && GEN_STATE[GenProp0082, Bacillus]
rule "2354|exodeoxyribonuclease III"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00195' )
	txn1 : Taxon( parentNames contains 'Bacillus' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2354");
	a.setCommonName("exodeoxyribonuclease III");
	a.setEcNumbers("3.1.11.2");
	a.setGeneSymbol("exoA");
	a.setGoIds("GO:0006281,GO:0008853");
	a.setRoleIds("132");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end