#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2279 THIS_HMM_HIT[TIGR00060] && GEN_STATE[GenProp0006,Bacteria]
rule "DEMO rule for NEW METHOD - HMM_plus_Lineage GenProp0006=superkingdom"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00060' )
	 and
	 txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2279");
	 a.setGoIds("GO:0003735,GO:0006412,GO:0022625,GO:0019843");
	 a.setCommonName("50S ribosomal protein L18");
	 a.setGeneSymbol("rplR");
	 a.setRoleIds("158");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end