#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2503 DEFAULT_METHOD[GB|ACA55393.1]
rule "protein-glutamine gamma-glutamyltransferase"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA55393.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2503");
	 a.setGoIds("GO:0003810,GO:0030436");
	 a.setEcNumbers("2.3.2.13");
	 a.setRoleIds("705");
	 a.setCommonName("protein-glutamine gamma-glutamyltransferase");
	 a.setGeneSymbol("tgl");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end