#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2566 DEFAULT_METHOD[SP|P13703]
rule "hydroxymethylglutaryl-CoA lyase"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P13703', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2566");
	 a.setGoIds("GO:0004419,GO:0006520");
	 a.setEcNumbers("4.1.3.4");
	 a.setRoleIds("109");
	 a.setCommonName("hydroxymethylglutaryl-CoA lyase");
	 a.setGeneSymbol("mvaB");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end