#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2438 DEFAULT_METHOD[RF|YP_001781263.1]
rule "2438|TPP-dependent acetoin dehydrogenase complex, E1 component, alpha subunit after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_001781263.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2438");
	a.setCommonName("TPP-dependent acetoin dehydrogenase complex, E1 component, alpha subunit");
	a.setEcNumbers("1.1.1.-");
	a.setGeneSymbol("acoA");
	a.setGoIds("GO:0016616,GO:0045150");
	a.setRoleIds("110,114");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end