#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2315 THIS_HMM_HIT[TIGR01009] && GEN_STATE[GenProp0006,Bacteria]
rule "ribosomal protein S3, rpsC by HMM in superkingdom BACTERIA"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01009' )
	 and
	 txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2315");
	 a.setCommonName("30S ribosomal protein S3");
	 a.setRoleIds("158");
	 a.setGeneSymbol("rpsC");
	 a.setGoIds("GO:0003735,GO:0006412,GO:0022627");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end