#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2355 THIS_HMM_HIT[TIGR00239] && GEN_STATE[GenProp0082, Bacillus]
rule "2355|2-oxoglutarate dehydrogenase, E1 component"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00239' )
	txn1 : Taxon( parentNames contains 'Bacillus' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2355");
	a.setCommonName("2-oxoglutarate dehydrogenase, E1 component");
	a.setEcNumbers("1.2.4.2");
	a.setGeneSymbol("odhA");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end