#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2567 DEFAULT_METHOD[SP|P0ACJ0]
rule "2567|leucine-responsive regulatory protein"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|P0ACJ0', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2567");
	a.setCommonName("leucine-responsive regulatory protein");
	a.setEcNumbers(" ");
	a.setGeneSymbol("lrp");
	a.setGoIds("GO:0003700,GO:0006355,GO:0015820");
	a.setRoleIds("261");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end