#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2452 DEFAULT_METHOD[GB|EDK32590.1]
rule "small, acid-soluble spore protein tlp MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|EDK32590.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2452");
	 a.setGoIds("GO:0003824,GO:0030436");
	 a.setRoleIds("705");
	 a.setCommonName("small, acid-soluble spore protein tlp");
	 a.setGeneSymbol("tlp");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end