#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2602 THIS_HMM_HIT[TIGR02363] && NEAR_HMM_HIT[2000,TIGR02364] && !THIS_HMM_HIT[TIGR02365]
rule "PTS-dependent dihydroxyacetone kinase, DhaK subunit"
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02363' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02364' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	gene2 : Feature( eval(gene2.isWithin(gene1, 2000)) )
	not HmmHit( program=='hmm', hitId=='TIGR02365', queryId == gene2.featureId )
	
 then
	 Annotation a = new Annotation("2602");
	 a.setGoIds("GO:0006071,GO:0016772");
	 a.setEcNumbers("2.7.-.-");
	 a.setRoleIds("184");
	 a.setCommonName("PTS-dependent dihydroxyacetone kinase, DhaK subunit");
	 a.setGeneSymbol("dhaK");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end