#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2482 DEFAULT_METHOD[GB|ACA46111.1]
rule "2482|guanine deaminase after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA46111.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2482");
	a.setCommonName("guanine deaminase");
	a.setEcNumbers("3.5.4.3");
	a.setGeneSymbol("guaD");
	a.setGoIds("GO:0008892,GO:0006144");
	a.setRoleIds("122");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end