#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2653 THIS_BLAST_HIT[GB|ABV05505.1, 250, 95, 95, 70, 5, 0]
rule "RNase III-binding regulator YmdB"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABV05505.1', 
			bitScore >= 250,
			hitPercentLength >= 95,
			queryPercentLength >= 95,  
			percentIdentity >= 70,
			hitQueryLengthRatio <= 5 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2653");
	 a.setGoIds("GO:0005515,GO:0030234,GO:0043086");
	 a.setRoleIds("129");
	 a.setCommonName("RNase III-binding regulator YmdB");
	 a.setGeneSymbol("ymdB");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end
