#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2510 DEFAULT_METHOD[GB|ABS39804.1]
rule "chemotaxis protein CheX after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABS39804.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2510");
	 a.setGoIds("GO:0003824,GO:0006935");
	 a.setRoleIds("188");
	 a.setCommonName("chemotaxis protein CheX");
	 a.setGeneSymbol("cheX");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end