#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2563 DEFAULT_METHOD[SP|P0AEG1]
rule "dipeptide ABC transporter, permease protein DppC"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P0AEG1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2563");
	 a.setGoIds("GO:0005887,GO:0015440,GO:0042936,GO:0042938");
	 a.setRoleIds("142");
	 a.setCommonName("dipeptide ABC transporter, permease protein DppC");
	 a.setGeneSymbol("dppC");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end