#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2559 DEFAULT_METHOD[GB|ACA54202.1]
rule "chemotaxis protein MotA after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA54202.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2559");
	 a.setGoIds("GO:0001539,GO:0003774");
	 a.setRoleIds("188");
	 a.setCommonName("chemotaxis protein MotA");
	 a.setGeneSymbol("motA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end