#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2536 DEFAULT_METHOD[SP|P19940]
rule "RNA polymerase sigma-G factor"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P19940', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2536");
	 a.setGoIds("GO:0006352,GO:0016987,GO:0042173");
	 a.setCommonName("RNA polymerase sigma-G factor");
	 a.setRoleIds("165,705");
	 a.setGeneSymbol("sigG");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end