#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2533 DEFAULT_METHOD[GB|ACA45034.1]
rule "chemotaxis protein CheA after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA45034.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2533");
	 a.setGoIds("GO:0000155,GO:0000160,GO:0004673,GO:0004871,GO:0006935,GO:0016310,GO:0016311");
	 a.setEcNumbers("2.7.13.3");
	 a.setRoleIds("188,699");
	 a.setCommonName("chemotaxis protein CheA");
	 a.setGeneSymbol("cheA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end