#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2288 THIS_HMM_HIT[TIGR00009] && GEN_STATE[GenProp0006,Bacteria]
rule "2288|50S ribosomal protein L28 by HMM in BACTERIA"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00009' )
	txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2288");
	a.setCommonName("50S ribosomal protein L28");
	a.setEcNumbers(" ");
	a.setGeneSymbol("rpmB");
	a.setGoIds("GO:0003735,GO:0006412,GO:0022625");
	a.setRoleIds("158");
	a.setConfidence();
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end