#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2526 DEFAULT_METHOD[GB|ACA55266.1]
rule "N(5)-(carboxyethyl)ornithine synthase"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA55266.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2526");
	 a.setGoIds("GO:0019794,GO:0047126");
	 a.setEcNumbers("1.5.1.24");
	 a.setRoleIds("109");
	 a.setCommonName("N(5)-(carboxyethyl)ornithine synthase");
	 a.setGeneSymbol("ceo");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end