#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2429 DEFAULT_METHOD[RF|YP_001387477.1]
rule "arginine/ornithine antiporter after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001387477.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2429");
	 a.setGoIds("GO:0000064,GO:0015181,GO:0015297,GO:0015809,GO:0015822");
	 a.setRoleIds("142");
	 a.setCommonName("arginine/ornithine antiporter");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end