#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2655 DEFAULT_METHOD[SP|P63201]
rule "glutamate-based acid resistance transcriptional activator GadW"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P63201', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2655");
	 a.setGoIds("GO:0005737,GO:0006355,GO:0030528,GO:0010447");
	 a.setRoleIds("261");
	 a.setCommonName("glutamate-dependent acid resistance transcriptional activator GadW");
	 a.setGeneSymbol("gadW");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end