#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2482 DEFAULT_METHOD[GB|ACA46111.1]
rule "guanine deaminase after MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA46111.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2482");
	 a.setGoIds("GO:0008892,GO:0006144");
	 a.setEcNumbers("3.5.4.3");
	 a.setRoleIds("122");
	 a.setCommonName("guanine deaminase");
	 a.setGeneSymbol("guaD");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end