#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2443 DEFAULT_METHOD[GB|ACA56469.1]
rule "2443|transcriptional antiterminator, LicT after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA56469.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2443");
	a.setCommonName("transcriptional antiterminator, LicT");
	a.setEcNumbers(" ");
	a.setGeneSymbol("licT");
	a.setGoIds("GO:0006355,GO:0030401,GO:0032950");
	a.setRoleIds("262");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end