#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2665 THIS_BLAST_HIT[GB|AAW40487.1, 700, 90, 90, 50, 5, 0]
rule "2665|lysine 2,3-aminomutase/beta-lysine N-acetyltransferase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|AAW40487.1', 
				bitScore >= 700, 
				hitPercentLength >= 90, 
				queryPercentLength >= 90, 
				percentIdentity >= 50, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2665");
	a.setCommonName("lysine 2,3-aminomutase/beta-lysine N-acetyltransferase");
	a.setEcNumbers("5.4.3.2 2.3.1.-");
	a.setGeneSymbol("ablAB");
	a.setGoIds("GO:0050066,GO:0016747,GO:0042398");
	a.setRoleIds("149");
	a.setConfidence(95);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end