#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2619 THIS_HMM_HIT[TIGR00635] && THIS_HMM_HIT[TIGR00084]
rule "2619|Holliday junction DNA helicase RuvA/RuvB"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00635' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR00084' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2619");
	a.setCommonName("Holliday junction DNA helicase RuvA/RuvB");
	a.setEcNumbers("3.6.1.-");
	a.setGeneSymbol("ruvAB");
	a.setGoIds("GO:0006310,GO:0009378,GO:0009379");
	a.setRoleIds("132");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end