#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2526 DEFAULT_METHOD[GB|ACA55266.1]
rule "2526|N(5)-(carboxyethyl)ornithine synthase"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA55266.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2526");
	a.setCommonName("N(5)-(carboxyethyl)ornithine synthase");
	a.setEcNumbers("1.5.1.24");
	a.setGeneSymbol("ceo");
	a.setGoIds("GO:0019794,GO:0047126");
	a.setRoleIds("109");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end