#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2494 DEFAULT_METHOD[GB|ABS40524.1]
rule "deoxyribonucleoside regulator"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABS40524.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2494");
	 a.setGoIds("GO:0003700,GO:0006355");
	 a.setRoleIds("261");
	 a.setCommonName("deoxyribonucleoside regulator");
	 a.setGeneSymbol("deoR");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end