#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2533 DEFAULT_METHOD[GB|ACA45034.1]
rule "2533|chemotaxis protein CheA after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA45034.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2533");
	a.setCommonName("chemotaxis protein CheA");
	a.setEcNumbers("2.7.13.3");
	a.setGeneSymbol("cheA");
	a.setGoIds("GO:0000155,GO:0000160,GO:0004673,GO:0004871,GO:0006935,GO:0016310,GO:0016311");
	a.setRoleIds("188,699");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end