#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2578 DEFAULT_METHOD[SP|Q47155]
rule "2578|DNA polymerase IV"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|Q47155', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2578");
	a.setCommonName("DNA polymerase IV");
	a.setEcNumbers("2.7.7.7");
	a.setGeneSymbol("dinB");
	a.setGoIds("GO:0003887,GO:0006281");
	a.setRoleIds("132");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end