#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2674 THIS_HMM_HIT[TIGR03827] && GEN_STATE[GenProp0078, Euryarchaeota]
rule "2674|beta-lysine N-acetyltransferase"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR03827' )
	txn1 : Taxon( parentNames contains 'Euryarchaeota' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2674");
	a.setCommonName("beta-lysine N-acetyltransferase");
	a.setEcNumbers("2.3.1.-");
	a.setGeneSymbol("ablB");
	a.setGoIds("GO:0016747,GO:0042398");
	a.setRoleIds("149");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end