#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2520 DEFAULT_METHOD[RF|YP_001781847.1]
rule "glycerate kinase"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001781847.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2520");
	 a.setEcNumbers("2.7.1.31");
	 a.setGoIds("GO:0008887,GO:0009436");
	 a.setCommonName("glycerate kinase");
	 a.setRoleIds("184");
	 a.setGeneSymbol("glxK");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end