#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2635 THIS_BLAST_HIT[SP|P28629, 1200, 95, 95, 80, 3, 0]
rule "arginine decarboxylase, acid-induced (adiA)."
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|P28629', 
			bitScore >= 1200,
			hitPercentLength >= 95,
			queryPercentLength >= 95,  
			percentIdentity >= 80,
			hitQueryLengthRatio <= 3 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2635");
	 a.setGoIds("GO:0008792,GO:0010248");
	 a.setEcNumbers("4.1.1.19");
	 a.setRoleIds("104");
	 a.setCommonName("biodegradative arginine decarboxylase");
	 a.setGeneSymbol("adiA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end