#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2499 DEFAULT_METHOD[GB|ACA54005.1]
rule "putative hydroxyethylthiazole kinase"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA54005.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2499");
	 a.setGoIds("GO:0004417,GO:0009228");
	 a.setRoleIds("162");
	 a.setCommonName("putative hydroxyethylthiazole kinase");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end