#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2636 THIS_BLAST_HIT[RF|NP_301087.1, 350, 95, 92, 80, 5, 0]
rule "2636|arginine decarboxylase, pyruvoyl-dependent"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|NP_301087.1', 
				bitScore >= 350, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2636");
	a.setCommonName("arginine decarboxylase, pyruvoyl-dependent");
	a.setEcNumbers("4.1.1.19");
	a.setGeneSymbol("aaxB");
	a.addGoIds("GO:0008792");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end