#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2336 DEFAULT_METHOD[OMNI|NTL01CV3272] && GEN_PROP[GenProp0823, 0.15]
rule "2336|Default-mode rule, to work eventually with HMM for VioE"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='OMNI|NTL01CV3272', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	genprop1 : GenomeProperty( this['id'] == 'GenProp0823', this['value'] >= 0.15 )
	gene1 : Feature( properties contains genprop1, featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2336");
	a.setCommonName("violacein biosynthesis monooxygenase VioC");
	a.setEcNumbers("1.-.-.-");
	a.setGeneSymbol("vioC");
	a.setRoleIds("94");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end