#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2500 DEFAULT_METHOD[GB|ACA45288.1]
rule "2500|dihydroorotate dehydrogenase, electron transfer subunit"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ACA45288.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2500");
	a.setCommonName("dihydroorotate dehydrogenase, electron transfer subunit");
	a.setEcNumbers(" ");
	a.setGeneSymbol("pyrK");
	a.setGoIds("GO:0004152,GO:0009220");
	a.setRoleIds("126");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end