#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2532 DEFAULT_METHOD[GB|AAO36263.1]
rule "chemotaxis protein CheC acter MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|AAO36263.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2532");
	 a.setGoIds("GO:0005515,GO:0006935,GO:0016787,GO:0016791");
	 a.setEcNumbers("3.-.-.-");
	 a.setRoleIds("188");
	 a.setCommonName("chemotaxis protein CheC");
	 a.setGeneSymbol("cheC");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end