#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2622 THIS_HMM_HIT[PF01174] && NEAR_HMM_HIT[500,TIGR00343]
rule "2622|pyridoxal phosphate synthase, Pdx2 subunit"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF01174' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR00343' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	gene2 : Feature( eval(gene2.isWithin(gene1, 500)) )


then
	Annotation a = new Annotation("2622");
	a.setCommonName("pyridoxal 5'-phosphate synthase, glutaminase subunit Pdx2");
	a.setGeneSymbol("pdxT");
	a.addGoIds("GO:0042823");
	a.setRoleIds("83");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end