#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2442 DEFAULT_METHOD[GB|ABS42103.1]
rule "2442|sulfite reductase, subunit C after MGAT curation Clostridium"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|ABS42103.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2442");
	a.setCommonName("sulfite reductase, subunit C");
	a.setEcNumbers("1.8.-.-");
	a.setGeneSymbol("asrC");
	a.setGoIds("GO:0006790,GO:0016002");
	a.setRoleIds("106");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.JOC_MGAT_SUBFAM);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end