#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2380 THIS_BLAST_HIT[RF|YP_026523, 625, 80,  95, 95, 5, 1]
rule "2380|alanine racemase, spore-specifc"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='RF|YP_026523', 
				bitScore >= 625, 
				hitPercentLength >= 80, 
				queryPercentLength >= 95, 
				percentIdentity >= 95, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2380");
	a.setCommonName("alanine racemase, spore-specific");
	a.setEcNumbers("5.1.1.1");
	a.setGeneSymbol("alr");
	a.setGoIds("GO:0043592,GO:0009847,GO:0030170,GO:0008784,GO:0009252");
	a.setRoleIds("89,705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end