#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2626 THIS_HMM_HIT[TIGR01111] && THIS_HMM_HIT[TIGR01149]
rule "2626|tetrahydromethanopterin S-methyltransferase, subunit A/G"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01111' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01149' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2626");
	a.setCommonName("tetrahydromethanopterin S-methyltransferase, subunit A/G");
	a.setEcNumbers("2.1.1.86");
	a.setGeneSymbol("mtrAG");
	a.setGoIds("GO:0006814,GO:0016020,GO:0019386,GO:0030269");
	a.setRoleIds("145,184");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end