#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2631 DEFAULT_METHOD[GB|AAF10419.1]
rule "5-nitroimidazole-class antibiotic resistance protein"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|AAF10419.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2631");
	 a.setGoIds("GO:0003824,GO:0046677");
	 a.setEcNumbers("1.-.-.-");
	 a.setRoleIds("94");
	 a.setCommonName("5-nitroimidazole-class antibiotic resistance protein");
	 a.setGeneSymbol("nim");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end