#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2302 THIS_HMM_HIT[TIGR01032] && GEN_STATE[GenProp0006,Bacteria]
rule "2302|50S ribosomal protein L20 by HMM in BACTERIA"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01032' )
	txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2302");
	a.setCommonName("50S ribosomal protein L20");
	a.setEcNumbers(" ");
	a.setGeneSymbol("rplT");
	a.setGoIds("GO:0003735,GO:0006412,GO:0022625,GO:0019843");
	a.setRoleIds("158");
	a.setConfidence();
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end