#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2664 THIS_HMM_HIT[TIGR02363] && THIS_HMM_HIT[TIGR02365]
rule "2664|dihydroxyacetone kinase, K/L subunit"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02363' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02365' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2664");
	a.setCommonName("dihydroxyacetone kinase, subunit I/II");
	a.setEcNumbers("2.7.1.-");
	a.setGeneSymbol("dhaKL");
	a.setGoIds("GO:0008152:,,GO:0016301:");
	a.setRoleIds("703");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end