#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2627 THIS_BLAST_HIT[RF|YP_021914.2, 251, 85, 85, 50, 10, 0] && THIS_HMM_HIT[PF05738] && THIS_HMM_HIT[TIGR01167]
rule "LPXTG-anchored collagen adhesion protein"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_021914.2', 
			bitScore >= 251,
			hitPercentLength >= 85,
			queryPercentLength >= 85,  
			percentIdentity >= 50,
			hitQueryLengthRatio <= 10 
		)
	 and
	 hmm_hit1 : HmmHit( program=='hmm', hitId=='PF05738' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01167' )
	gene1 : Feature( featureId == blast_hit1.queryId, featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2627");
	 a.setRoleIds("88");
	 a.setCommonName("LPXTG-anchored collagen adhesion protein");
	 a.setGoIds("GO:0031589,GO:0005518");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end