#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2607 THIS_HMM_HIT[TIGR02857] && THIS_HMM_HIT[TIGR02868]
rule "2607|thiol reductant ABC exporter, CydCD subunit"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02857' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02868' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2607");
	a.setCommonName("thiol reductant ABC exporter, CydCD fusion protein");
	a.setEcNumbers(" ");
	a.setGeneSymbol("cydCD");
	a.setGoIds("GO:0033230,GO:0033228,GO:0005887,GO:0005524,GO:0055051");
	a.setRoleIds("142");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	modify(gene1);
end