#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2600 THIS_HMM_HIT[TIGR00325] && THIS_HMM_HIT[TIGR01750]
rule "2600|UDP-3-O-3-hydroxymyristoyl N-acetylglucosamine deacetylase/(3R)-hydroxymyristoyl-(acyl-carrier-protein) dehydratase"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00325' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01750' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2600");
	a.setCommonName("UDP-3-O-3-hydroxymyristoyl N-acetylglucosamine deacetylase/(3R)-hydroxymyristoyl-(acyl-carrier-protein) dehydratase");
	a.setEcNumbers("3.5.1.- 4.2.1.-");
	a.setGeneSymbol("lpxC/fabZ");
	a.setGoIds("GO:0006633,GO:0016836,GO:0009245,GO:0008759");
	a.setRoleIds("90,176");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end