#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2403 THIS_BLAST_HIT[GB|AAP12212.1, 450, 95, 92, 80, 5, 0]
rule "transcriptional regulator PlcR"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|AAP12212.1', 
			bitScore >= 450,
			hitPercentLength >= 95,
			queryPercentLength >= 92,  
			percentIdentity >= 80,
			hitQueryLengthRatio <= 5 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2403");
	 a.setGoIds("GO:0042277,GO:0052100,GO:0003677,GO:0006355,GO:0016563");
	 a.setRoleIds("261");
	 a.setCommonName("global transcriptional regulator PlcR");
	 a.setGeneSymbol("plcR");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end