#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2508 DEFAULT_METHOD[RF|YP_001781804.1]
rule "putative (R)-2-hydroxyglutaryl-CoA dehydratase, beta subunit"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001781804.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2508");
	 a.setGoIds("GO:0019665,GO:0043717");
	 a.setRoleIds("109,114");
	 a.setCommonName("putative (R)-2-hydroxyglutaryl-CoA dehydratase, beta subunit");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end