#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2593 DEFAULT_METHOD[GB|CAL84266.1]
rule "2593|flagellar glycosylation island glycosyltransferase, CBO2705 family"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|CAL84266.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2593");
	a.setCommonName("flagellar glycosylation island glycosyltransferase, CBO2705 family");
	a.setEcNumbers("2.4.1.-");
	a.setGeneSymbol(" ");
	a.setGoIds("GO:0000271,GO:0016757");
	a.setRoleIds("90,91");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end