#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2605 THIS_HMM_HIT[TIGR02425] && THIS_HMM_HIT[TIGR02427]
rule "3-oxoadipate enol-lactone hydrolase/4-carboxymuconolactone decarboxylase"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR02425' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR02427' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2605");
	 a.setGoIds("GO:0042952,GO:0047570,GO:0047575");
	 a.setEcNumbers("3.1.1.24 4.1.1.44");
	 a.setCommonName("3-oxoadipate enol-lactone hydrolase/4-carboxymuconolactone decarboxylase");
	 a.setRoleIds("184");
	 a.setGeneSymbol("pcaDC");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end