#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2323 THIS_HMM_HIT[PF00411] && GEN_STATE[GenProp0006,Bacteria]
rule "ribosomal protein S11, rpsK by HMM in superkingdom BACTERIA"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF00411' )
	 and
	 txn1 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2323");
	 a.setCommonName("30S ribosomal protein S11");
	 a.setRoleIds("158");
	 a.setGeneSymbol("rpsK");
	 a.setGoIds("GO:0003735,GO:0006412,GO:0022627");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end