#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2478 DEFAULT_METHOD[GB|ACA57104.1]
rule "S-methyl-5-thioribose-1-phosphate isomerase after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA57104.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2478");
	 a.setGoIds("GO:0019509,GO:0046523");
	 a.setEcNumbers("5.3.1.23");
	 a.setRoleIds("71");
	 a.setCommonName("S-methyl-5-thioribose-1-phosphate isomerase");
	 a.setGeneSymbol("mtnA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end