#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2695 THIS_HMM_HIT[TIGR03554]
rule "2695|F420-binding GO term by HMM"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR03554' )
	gene1 : Feature( featureId == hmm_hit1.queryId )


then
	Annotation a = new Annotation("2695");
	a.addGoIds("GO:0070967");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	//update(gene1);
end