#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2691 THIS_BLAST_HIT[SP|Q58820, 360, 95, 92, 55, 3, 0] && GEN_STATE[GenProp0006, Archaea]
rule "L-sulfolactate dehydrogenase ComC by BLAST"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|Q58820', 
			bitScore >= 360,
			hitPercentLength >= 95,
			queryPercentLength >= 92,  
			percentIdentity >= 55,
			hitQueryLengthRatio <= 3 
		)
	 and
	 txn1 : Taxon( parentNames contains 'Archaea' )
	gene1 : Feature( featureId == blast_hit1.queryId, taxon == txn1 )
	
 then
	 Annotation a = new Annotation("2691");
	 a.setGoIds("GO:0019295,GO:0050578");
	 a.setEcNumbers("1.1.1.272");
	 a.setRoleIds("76,159");
	 a.setCommonName("L-sulfolactate dehydrogenase");
	 a.setGeneSymbol("comC");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end