#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2684 THIS_HMM_HIT[PF06192] && NEAR_HMM_HIT[1000, TIGR01409] && !NEAR_HMM_HIT[5000, TIGR02164]
rule "2684|TorD homolog that is not TorD itself because it is not near TorA."
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF06192' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR01409' )
	gene1 : Feature( featureId == hmm_hit1.queryId )
	gene2 : Feature( featureId == hmm_hit2.queryId, eval(gene2.isWithin(gene1, 1000)) )
	gene3 : Feature( genome == gene1.genome, eval(gene3.isWithin(gene1, 5000)) )
	not HmmHit( program=='hmm', hitId=='TIGR02164', queryId == gene3.featureId )

then
	Annotation a = new Annotation("2684");
	a.setCommonName("TAT-signal peptide-binding chaperone, TorD family");
	a.setGeneSymbol("NULL");
	a.addGoIds("GO:0051082,GO:0043953");
	a.setRoleIds("95,97");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end