#created on: Jan 13, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2408 THIS_BLAST_HIT[SP|P35158, 175, 95, 92, 50, 5, 0] && NEAR_BLAST_HIT[800, SP|P35150, 275, 95, 92, 40, 5, 0]
rule "2408|spore maturation protein B"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|P35158', 
				bitScore >= 175, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 50, 
				hitQueryLengthRatio <= 5 )
	blast_hit2 : BlastHit( program=='blastp', 
				hitId=='SP|P35150', 
				bitScore >= 275, 
				hitPercentLength >= 95, 
				queryPercentLength >= 92, 
				percentIdentity >= 40, 
				hitQueryLengthRatio <= 5 )
	gene1 : Feature( featureId == blast_hit1.queryId )
	gene2 : Feature( featureId == blast_hit2.queryId, eval(gene2.isWithin(gene1, 800)) )


then
	Annotation a = new Annotation("2408");
	a.setCommonName("spore maturation protein B");
	a.setGeneSymbol("spmB");
	a.addGoIds("GO:0034301");
	a.addRoleIds("705");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.INIT_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end