#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2682 THIS_BLAST_HIT[GB|BAA09026.1, 250, 95, 92, 30, 5, 0] && THIS_HMM_HIT[PF04234] && THIS_HMM_HIT[PF05425]
rule "copper homeostasis protein CopCD"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|BAA09026.1', 
			bitScore >= 250,
			hitPercentLength >= 95,
			queryPercentLength >= 92,  
			percentIdentity >= 30,
			hitQueryLengthRatio <= 5 
		)
	 and
	 hmm_hit1 : HmmHit( program=='hmm', hitId=='PF04234' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='PF05425' )
	gene1 : Feature( featureId == blast_hit1.queryId, featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2682");
	 a.setCommonName("copper homeostasis protein CopCD");
	 a.setRoleIds("145");
	 a.setGeneSymbol("copCD");
	 a.addGoIds("GO:0046688,GO:0005507");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end