#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2551 DEFAULT_METHOD[RF|YP_001783274.1]
rule "sporulation initiation inhibitor protein Soj"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001783274.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2551");
	 a.setGoIds("GO:0016887,GO:0030436,GO:0042174");
	 a.setRoleIds("129,705");
	 a.setCommonName("sporulation initiation inhibitor protein Soj");
	 a.setGeneSymbol("soj");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end