#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2390 THIS_BLAST_HIT[RF|YP_082716.1, 290, 95, 92, 90, 5, 0]
rule "exosporium protein Y"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_082716.1', 
			bitScore >= 290,
			hitPercentLength >= 95,
			queryPercentLength >= 92,  
			percentIdentity >= 90,
			hitQueryLengthRatio <= 5 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2390");
	 a.setGoIds("GO:0003674,GO:0034301,GO:0043592,GO:0070499");
	 a.setRoleIds("705");
	 a.setCommonName("exosporium protein Y");
	 a.setGeneSymbol("exsY");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end