#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2354 THIS_HMM_HIT[TIGR00195] && GEN_STATE[GenProp0082, Bacillus]
rule "exodeoxyribonuclease III"
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00195' )
	 and
	 txn1 : Taxon( parentNames contains 'Bacillus' )
	gene1 : Feature( taxon == txn1, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2354");
	 a.setGoIds("GO:0006281,GO:0008853");
	 a.setEcNumbers("3.1.11.2");
	 a.setRoleIds("132");
	 a.setCommonName("exodeoxyribonuclease III");
	 a.setGeneSymbol("exoA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end