#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2516 DEFAULT_METHOD[GB|ACA44725.1]
rule "flagellin after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA44725.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2516");
	 a.setGoIds("GO:0001539,GO:0005198,GO:0009288,GO:0009420");
	 a.setCommonName("flagellin");
	 a.setRoleIds("188");
	 a.setGeneSymbol("fliC");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end