#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2663 THIS_HMM_HIT[TIGR01356] && THIS_HMM_HIT[TIGR00017]
rule "bifunctional 3-phosphoshikimate 1-carboxyvinyltransferase/cytidylate kinase"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR01356' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='TIGR00017' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )
	
 then
	 Annotation a = new Annotation("2663");
	 a.setGoIds("GO:0003866,GO:0009423");
	 a.setEcNumbers("2.5.1.19 2.7.4.14");
	 a.setRoleIds("70,124");
	 a.setCommonName("bifunctional 3-phosphoshikimate 1-carboxyvinyltransferase/cytidylate kinase");
	 a.setGeneSymbol("aroA/cmk");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end