#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2632 THIS_HMM_HIT[PF02518] && THIS_HMM_HIT[PF01584] && THIS_HMM_HIT[PF01627]
rule "CheA signal transduction histidine kinase"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF02518' )
	 and
	 hmm_hit2 : HmmHit( program=='hmm', hitId=='PF01584' )
	 and
	 hmm_hit3 : HmmHit( program=='hmm', hitId=='PF01627' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId, featureId == hmm_hit3.queryId )
	
 then
	 Annotation a = new Annotation("2632");
	 a.setCommonName("CheA signal transduction histidine kinase");
	 a.setGeneSymbol("cheA");
	 a.addGoIds("GO:0000156 GO:0000160 GO:0006355 ");
	 a.addEcNumbers("2.7.13.3");
	 a.addRoleIds("129 263 699");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end