#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2604 THIS_HMM_HIT[PF00005] && THIS_HMM_HIT[PF03412]
rule "2604|bacteriocin ABC transporter, metallopeptidase/ATP-binding subunit"
no-loop true
when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='PF00005' )
	hmm_hit2 : HmmHit( program=='hmm', hitId=='PF03412' )
	gene1 : Feature( featureId == hmm_hit1.queryId, featureId == hmm_hit2.queryId )


then
	Annotation a = new Annotation("2604");
	a.setCommonName("bacteriocin ABC transporter, metallopeptidase/ATP-binding subunit");
	a.setEcNumbers("3.4.24.-");
	a.setGoIds("GO:0005524,GO:0006508,GO:0006810,GO:0008233,GO:0009898,GO:0042626,GO:0043192");
	a.setRoleIds("94,141");
	a.setConfidence(90);
	a.setSpecificity(SpecificityType.FAMILY_COMPLETE);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end