#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2346 THIS_HMM_HIT[TIGR03652] && GEN_STATE[GenProp0008, YES] && GEN_STATE[GenProp0006, Bacteria]
rule "iron-sulfur cluster repair protein RIC - add pathogen terms if pathogen"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR03652' )
	 and
	 txn1 : Taxon( parentNames contains 'YES' )
	 and
	 txn2 : Taxon( parentNames contains 'Bacteria' )
	gene1 : Feature( taxon == txn1, taxon == txn2, featureId == hmm_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2346");
	 a.addGoIds("GO:0052059");
	 a.addRoleIds("149");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end