#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2507 DEFAULT_METHOD[RF|YP_001781794.1]
rule "putative esterase"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='RF|YP_001781794.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2507");
	 a.setGoIds("GO:0008152,GO:0016788");
	 a.setRoleIds("703");
	 a.setCommonName("putative esterase");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end