#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2578 DEFAULT_METHOD[SP|Q47155]
rule "DNA polymerase IV"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='SP|Q47155', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2578");
	 a.setGoIds("GO:0003887,GO:0006281");
	 a.setEcNumbers("2.7.7.7");
	 a.setRoleIds("132");
	 a.setCommonName("DNA polymerase IV");
	 a.setGeneSymbol("dinB");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end