#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2436 THIS_HMM_HIT[TIGR00121] && !THIS_HMM_HIT[PF08279] && !THIS_HMM_HIT[TIGR00122]
rule "biotin-[acetyl-CoA-carboxylase] ligase (NOT with repressor domain)"
no-loop true
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00121' )
	gene1 : Feature( featureId == hmm_hit1.queryId )
	not HmmHit( program=='hmm', hitId=='PF08279', queryId == gene1.featureId )
	not HmmHit( program=='hmm', hitId=='TIGR00122', queryId == gene1.featureId )
	
 then
	 Annotation a = new Annotation("2436");
	 a.setGoIds("GO:0004077,GO:0009102");
	 a.setEcNumbers("6.3.4.15");
	 a.setCommonName("biotin-[acetyl-CoA-carboxylase] ligase");
	 a.setRoleIds("77,140");
	 a.setGeneSymbol("bpl");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end