#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2642 NEAR_HMM_HIT[2000, TIGR00541] && THIS_BLAST_HIT[GB|AAV65955.1, 550, 92, 92, 70, 5, 0]
rule "histidine:histamine antiporter"
 when
	hmm_hit1 : HmmHit( program=='hmm', hitId=='TIGR00541' )
	 and
	 blast_hit1 : BlastHit( program=='blastp', hitId=='GB|AAV65955.1', 
			bitScore >= 550,
			hitPercentLength >= 92,
			queryPercentLength >= 92,  
			percentIdentity >= 70,
			hitQueryLengthRatio <= 5 
		)
	gene1 : Feature( featureId == hmm_hit1.queryId )
	gene2 : Feature( featureId == blast_hit1.queryId, eval(gene2.isWithin(gene1, 2000)) )
	
 then
	 Annotation a = new Annotation("2642");
	 a.setGoIds("GO:0015300,GO:0051608,GO:0015817,GO:0005886");
	 a.setRoleIds("142");
	 a.setCommonName("histidine:histamine antiporter");
	 a.setGeneSymbol("hdcP");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end