#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2479 DEFAULT_METHOD[GB|ACA53818.1]
rule "aldolase, AraD/FucA family after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA53818.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2479");
	 a.setGoIds("GO:0008152,GO:0016832");
	 a.setCommonName("aldolase, AraD/FucA family");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end