#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2652 DEFAULT_METHOD[SP|P46889]
rule "2652|DNA translocase FtsK"
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='SP|P46889', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1)
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2652");
	a.setCommonName("DNA translocase FtsK");
	a.setGeneSymbol("ftsK");
	a.setGoIds("GO:0000910,GO:0015616");
	a.setRoleIds("93");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.EQUIVALOG);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end