#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2490 DEFAULT_METHOD[GB|ACA56416.1]
rule "ribonuclease Z after MGAT curation Clostridium"
no-loop true
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ACA56416.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2490");
	 a.setGoIds("GO:0042780,GO:0042781");
	 a.setEcNumbers("3.1.26.11");
	 a.setRoleIds("166");
	 a.setCommonName("ribonuclease Z");
	 a.setGeneSymbol("rnz");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end