#created on: Dec 1, 2009
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2440 DEFAULT_METHOD[GB|ABS39976.1]
rule "sulfite reductase, subunit A after MGAT curation Clostridium"
 when
	blast_hit1 : BlastHit( program=='blastp', hitId=='GB|ABS39976.1', 
				bitScore >= 160,
				hitPercentLength >= 90,
				queryPercentLength >= 90,  
				percentIdentity >= 80,
				hitQueryLengthRatio <= 5.1 
			)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("2440");
	 a.setGoIds("GO:0006790,GO:0009055,GO:0016002");
	 a.setEcNumbers("1.8.-.-");
	 a.setRoleIds("106");
	 a.setCommonName("sulfite reductase, subunit A");
	 a.setGeneSymbol("asrA");
	 gene1.addAssertedAnnotation(a);
	 update(gene1);
end