#created on: Jan 12, 2010
package org.jcvi.annotation.rules
import org.jcvi.annotation.facts.*;

// rule 2167 THIS_BLAST_HIT[GB|CAB46570.1, 800, 96, 96, 80, 3, 1]
rule "2167|bifunctional salicylate synthase YbtS, BLASTP OVERRULE level for yersiniabactin biosynthesis."
no-loop true
when
	blast_hit1 : BlastHit( program=='blastp', 
				hitId=='GB|CAB46570.1', 
				bitScore >= 800, 
				hitPercentLength >= 96, 
				queryPercentLength >= 96, 
				percentIdentity >= 80, 
				hitQueryLengthRatio <= 3 )
	gene1 : Feature( featureId == blast_hit1.queryId )


then
	Annotation a = new Annotation("2167");
	a.setCommonName("bifunctional salicylate synthase YbtS");
	a.setEcNumbers("5.4.4.2 4.1.3.-");
	a.setGeneSymbol("ybtS");
	a.setGoIds("GO:0016833,GO:0008909,GO:0019290");
	a.setRoleIds("707");
	a.setConfidence(97);
	a.setSpecificity(SpecificityType.OVER_EQUIV);
	gene1.addAssertedAnnotation(a);
	update(gene1);
end