#created on: Jun 10, 2009
package org.jcvi.annotation.rules;
import org.jcvi.annotation.facts.*;

#declare any global variables here

rule "BlastP Hit with a Taxonomy Restriction"
no-loop true

	when
		feature : Feature( )
		taxon : Taxon( parentNames contains "Firmicutes" ) from feature.taxon
		hit : BlastHit( program == "blastp", hitId == "RF|NP_844922.1",
			queryId == feature.featureId,
			bitScore >= 160, hitPercentLength >= 90,
			queryPercentLength >= 90,  percentIdentity >= 80,
			hitQueryLengthRatio <= 5.1)
		
	then
	    
	    Annotation a = new Annotation("Complete BlastP Hit Rule");
	    a.setConfidence(80.0);
	    a.setSpecificity(Annotation.EQUIVALOG);
	    a.setAssertionType(Annotation.EXACT);
	    a.addGoIds("GO:0043592,GO:0003674,GO:0008150");
	    a.setEcNumber("");
	    a.addRoleIds("705");
	    a.setCommonName("exosporium protein K");
	    a.setGeneSymbol("exsK");
	   	feature.addAssertedAnnotation(a);
		
		// System.out.println("Rule fires for hit " + hit.getHitId());		
		update( hit );
end


