#created on: Jun 10, 2009
package org.jcvi.annotation.rules;
import org.jcvi.annotation.facts.*;
import java.util.Arrays;

#declare any global variables here
rule "Simple BlastP Hit Rule"
no-loop true
	
	when
		hit : BlastHit( program == "blastp", hitId == "RF|NP_844922.1" )
		
	then 
		System.out.println("Simple BlastP Hit Rule "); // + hit.hitId);
		
end


rule "Complete BlastP Hit Rule"
no-loop true

	when
		hit : BlastHit(program == "blastp", hitId == "RF|NP_844922.1", 
		    $queryId : queryId,
			bitScore >= 160, hitPercentLength >= 90,
			queryPercentLength >= 90,  percentIdentity >= 80,
			hitQueryLengthRatio <= 5.1 )
		feat : Feature(featureId == $queryId)
	then
	    
	    Annotation a = new Annotation("Complete BlastP Hit Rule");
	    a.setConfidence(96.0);
	    a.setSpecificity(SpecificityType.INIT_EQUIV);
	    a.setAssertionType(Annotation.EXACT);
	    # set go_ids = GO:0043592 GO:0003674 GO:0008150
	    a.addGoIds(Arrays.asList("GO:0043592","GO:0003674","GO:0008150"));
	    // a.setEcNum(null);
	    a.addRoleId("705");
	    a.setCommonName("exosporium protein K");
	    a.setGeneSymbol("exsK");
	    feat.addAssertedAnnotation(a);
		
		System.out.println("Complete BlastP Hit Rule");
		System.out.println("hitPercentLength " + hit.getHitPercentLength());
		update( feat );
end


