#created on: Jun 10, 2009
package org.jcvi.annotation.rules;
import org.jcvi.annotation.facts.*;

rule "2645|lysine decarboxylase CadA"
when
	(or
		(and
			blast_hit : BlastHit( hitId=='GB|AAQ16631.1')
			gene1 : Feature( featureId == blast_hit.queryId )
		)
		(or
			(and
				blast_hit : BlastHit( hitId=='GB|AAQ16631.1' )
				gene1 : Feature( featureId == blast_hit.queryId )
			)
			(and
				hmm_hit1 : HmmHit( hitId=='TIGR00905' )
				gene1 : Feature( featureId == hmm_hit1.queryId )
				gene2 : Feature( eval(gene2.isWithin(gene1, 500)) )
			)
		)
	)
then      
	Annotation a = new Annotation("lysine decarboxylase CadA");
end
