#created on: Jun 10, 2009
package org.jcvi.annotation.rules;
import org.jcvi.annotation.facts.*;

rule "yersiniabactin import subunit YbtP"
 when
	blast_hit1 : BlastHit( program=="blastp", hitId=="RF|NP_993009.1", 
			bitScore >= 800,
			hitPercentLength >= 95,
			queryPercentLength >= 95,  
			percentIdentity >= 80,
			hitQueryLengthRatio <= 5 
		)
	gene1 : Feature( featureId == blast_hit1.queryId )
	
 then
	 Annotation a = new Annotation("yersiniabactin import subunit YbtP");
	 a.setCommonName("yersiniabactin ABC transporter, ATP-binding/permease protein");
	 a.setGeneSymbol("ybtP");
	 a.setRoleIds("145");
	 a.addGoIds("GO:0015891,GO:0042626:contributes_to,GO:0043190");
	 gene1.addAssertedAnnotation(a);
	 insert(a);
	 //modify(gene1);
end