#created on: Jun 10, 2009
package org.jcvi.annotation.rules;
import org.jcvi.annotation.facts.*;

rule "upgade GO process for endospore formers from sporulation to endospore"
    when
        geneA : Feature( )
	 	Taxon( parentNames contains "Firmicutes") from        geneA.taxon
		annot : Annotation( (goIds contains "GO:0008150") || (goIds contains "GO:0043936") ) from 	geneA.assignedAnnotation
 
    then
    	System.out.println(kcontext.getRule().getName());
        annot.setCommonName("endospore");
end

rule "Testing relational approach to specifying above rule"
    when
		annot : Annotation( (goIds contains "GO:0008150") || (goIds contains "GO:0043936") )
		txn : Taxon( parentNames contains "Firmicutes" )
        geneA : Feature( assignedAnnotation==annot, taxon==txn )
    then
    	System.out.println(kcontext.getRule().getName());
        annot.setCommonName("endospore");
end


