#created on: Jun 10, 2009
package org.jcvi.annotation.rules;
import org.jcvi.annotation.facts.*;

# Translating legacy rule
# (THIS_GO_TERM[GO:0030435] || THIS_GO_TERM[GO:0043936]) && GEN_PROP[GenProp0610, 0.6] && GEN_STATE[GenProp0078, Firmicutes]

rule "goal solution"
    when
 		genProp : GenomeProperty( id == 'GenProp0610', value >= 0.6 )
        gene	: Feature( properties contains genProp )
 		annot : Annotation( (goIds contains "GO:0030435") || (goIds contains "GO:0043936") ) from gene.assignedAnnotation
 		txn : Taxon( parentNames contains 'Firmicutes' ) from gene.taxon
    then
    	modify ( annot ) {
    		addGoId( "GO:0008150" ),
    		setCommonName( "endospore" )
    	}
end
