package org.jcvi.annotation.rules.genomeproperties
import org.jcvi.annotation.facts.*;
import java.util.ArrayList;

rule "Above Trusted Cutoff"
dialect "mvel"
	when
		h	: HmmHit( aboveTrustedHit == true, hitId : hitId )
		p	: FeatureProperty( id == hitId )
		f	: Feature ( featureId == h.queryId, properties not contains p )
 	then
 		modify( p ) { setValue(1) };
 		modify( f ) { addProperty(p) };
 		//System.out.println("hmm " + p.toString() + " value:" + p.getValue());
end


