#created on: Apr 6, 2010
package org.jcvi.annotation.rules.genomeproperties
import org.jcvi.annotation.facts.*;
import java.util.ArrayList;

rule "HMM Hit"
	when
		hit : HmmHit( aboveTrustedHit == true )
		p	: FeatureProperty( id == hit.hitId )
		f	: Feature ( featureId == hit.queryId, properties not contains p )
 	then
 		modify( p ) { setValue(1) };
 		modify( f ) { addProperty(p) };
 		if (hit.getHitId().equals("TIGR01240")) {
 			System.err.println("HMM Hit rule: " + hit.getHitId() + " " + hit.getQueryId());
		}
 		// TIGR00549 for FeatureProperty_101
 		// TIGR01240 for FeatureProperty_103
 end

rule "test HMM Hit"
	when
		hit : HmmHit( aboveTrustedHit == true, hitId == "TIGR01240" )
		p	: FeatureProperty( id == hit.hitId )
		f	: Feature ( featureId == hit.queryId, properties not contains p )
 	then
 		System.err.println("test HMM Hit rule: " + hit.getHitId() + " " + hit.getQueryId());
 end