#created on: Apr 6, 2010
package org.jcvi.annotation.rules.genomeproperties
import org.jcvi.annotation.facts.*;
import java.util.ArrayList;

rule "GenomeProperty state: none found"
	when
		gp : GenomeProperty( value == 0, state != PropertyState.NONE_FOUND )
 	then
 		gp.setState(PropertyState.NONE_FOUND);
 		//modify( gp ) { setState(PropertyState.NONE_FOUND) };
 		// System.out.println(gp.getState().toString() + " " + gp.getValue() + " " + gp.getThreshold() + " " + gp.toString());
end

rule "GenomeProperty state: yes"
	when
		gp : GenomeProperty( value == 1, state != PropertyState.YES )
 	then
 		gp.setState(PropertyState.YES);
 		System.out.println(gp.getState().toString() + " " + gp.getValue() + " " + gp.getThreshold() + " " + gp.toString());
 		//modify( gp ) { setState(PropertyState.YES) };
end

rule "GenomeProperty state: not supported"
	when
		gp : GenomeProperty( value > 0 && value < threshold, state != PropertyState.NOT_SUPPORTED )
 	then
 		gp.setState(PropertyState.NOT_SUPPORTED);
 		System.out.println(gp.getState().toString() + " " + gp.getValue() + " " + gp.getThreshold() + " " + gp.toString());
end

rule "GenomeProperty state: some evidence"
	when
		gp : GenomeProperty( value > 0 && value > threshold && value < 1, state != PropertyState.SOME_EVIDENCE )
 	then
 		gp.setState(PropertyState.SOME_EVIDENCE);
 		System.out.println(gp.getState().toString() + " " + gp.getValue() + " " + gp.getThreshold() + " " + gp.toString());
end