#created on: Apr 6, 2010
package org.jcvi.annotation.rules.genomeproperties
import org.jcvi.annotation.facts.*;
import java.util.ArrayList;

rule "GenomeProperty state: none found"
agenda-group "report"
	when
		gp 		: GenomeProperty( value == 0.0 )
 	then
 		System.out.println("NONE FOUND " + gp.getValue() + " " + gp.getThreshold() + " " + gp.toString());
  		modify( gp ) { setState(PropertyState.NONE_FOUND) };
 end

rule "GenomeProperty state: yes"
agenda-group "report"
	when
		gp : GenomeProperty( value == 1.0 )
 	then
 		System.out.println(gp.getState().toString() + " " + gp.getValue() + " " + gp.getThreshold() + " " + gp.toString());
 		modify( gp ) { setState(PropertyState.YES) };
end

rule "GenomeProperty state: not supported"
agenda-group "report"
	when
		gp : GenomeProperty( value > 0.0 && value < threshold )
 	then
 		System.out.println(gp.getState().toString() + " " + gp.getValue() + " " + gp.getThreshold() + " " + gp.toString());
		modify( gp ) { setState(PropertyState.NOT_SUPPORTED) };
 end

rule "GenomeProperty state: some evidence"
agenda-group "report"
	when
		gp : GenomeProperty( value > 0.0 && value > threshold && value < 1.0 )
 	then
 		System.out.println(gp.getState().toString() + " " + gp.getValue() + " " + gp.getThreshold() + " " + gp.toString());
 		modify( gp ) { setState(PropertyState.SOME_EVIDENCE) };
end