#created on: Apr 6, 2010
package org.jcvi.annotation.rules.genomeproperties
import org.jcvi.annotation.facts.*;
import java.util.ArrayList;

rule "GenomeProperty state: none found"
	when
		genomeprop : GenomeProperty( value == 0 )
 	then
 		genomeprop.put("state", "none found");
 		System.out.println("Setting state: " + genomeprop.get("state").toString());
end

rule "GenomeProperty state: yes"
	when
		genomeprop : GenomeProperty( value == 1 )
 	then
 		genomeprop.put("state", "yes");
 		System.out.println("Setting state: " + genomeprop.get("state").toString());
end

rule "GenomeProperty state: not supported"
	when
		genomeprop : GenomeProperty( value > 0 && value < threshold )
 	then
 		//genomeprop.put("state", "not supported");
 		genomeprop.setState(PropertyState.NOT_SUPPORTED);
 		System.out.println("Setting state: " + genomeprop.get("state").toString());
end

rule "GenomeProperty state: some evidence"
	when
		genomeprop : GenomeProperty( value > threshold && value < 1 )
 	then
 		genomeprop.put("state", "some evidence");
 		System.out.println("Setting state: " + genomeprop.get("state").toString());
end
