#created on: Apr 6, 2010
package org.jcvi.annotation.rules.genomeproperties
import org.jcvi.annotation.facts.*;

rule "GenomeProperty state none found"
	when
		gp 		: GenomeProperty( value == 0.0, state != PropertyState.NONE_FOUND )
 	then
 		System.out.println("NONE FOUND " + gp.getValue() + " " + gp.getThreshold() + " " + gp.toString());
 		// gp.setState(PropertyState.NONE_FOUND);
 		modify( gp ) { setState(PropertyState.NONE_FOUND) };
 end


