#created on: Apr 6, 2010
package org.jcvi.annotation.rules.genomeproperties
import org.jcvi.annotation.facts.*;
import java.util.ArrayList;

rule "GenomeProperty value calculation"
lock-on-active true
salience 10
	when
		engineReady			: EngineReady()
		genomeprop	 		: GenomeProperty()
		requiredRelations	: ArrayList()
				from collect( PropertyRelationship( type == RelationshipType.REQUIRED_BY, object == genomeprop ) )		
		numFilledComponents	: Double() 
				from accumulate(  r : PropertyRelationship()
					from requiredRelations,
				sum( r.getSubject().getValue() ) )

 	then 
		double numRequiredComponents = new Double(requiredRelations.size());
		double fractionFilledComponents = numFilledComponents / numRequiredComponents;
  		genomeprop.put("value", fractionFilledComponents);
  		System.out.println("Setting value " + genomeprop.toString());
   		update(genomeprop);
end
