#created on: Apr 6, 2010
package org.jcvi.annotation.rules.genomeproperties
import org.jcvi.annotation.facts.*;
import java.util.ArrayList;


rule "GenomeProperty value calculation"
	when
		genomeprop	 		: GenomeProperty( filledValue : filled )
		requiredRelations	: ArrayList()
				from collect( PropertyRelationship( subject : subject, type == RelationshipType.REQUIRED_BY, object == genomeprop ) )
		subject : Property( this == subject )		
		numFilledComponents	: Double( doubleValue != filledValue ) 
				from accumulate(  r : PropertyRelationship()
					from requiredRelations,
				sum( r.getSubject().getValue() ) )

 	then 
		double numRequiredComponents = new Double(requiredRelations.size());
		double fractionFilledComponents = (numRequiredComponents == 0) ? 0
								: numFilledComponents / numRequiredComponents;
		modify( genomeprop ) {
			setRequired(numRequiredComponents),
			setFilled(numFilledComponents),
			setValue(fractionFilledComponents)
		};
  		System.out.println(numFilledComponents + "/" +
	  				numRequiredComponents + " = " +
	  				fractionFilledComponents + " " + 
	  				genomeprop.toString());
 end
