#created on: Apr 6, 2010
package org.jcvi.annotation.rules.genomeproperties
import org.jcvi.annotation.facts.*;
import java.util.ArrayList;

rule "Test GenomeProperty filled calculation"
no-loop true
	when
		genomeprop	 		: GenomeProperty()
		requiredRelations	: ArrayList()
				from collect( PropertyRelationship( type == RelationshipType.REQUIRED_BY, object == genomeprop ) )		
		numFilledComponents	: Double() 
				from accumulate(  r : PropertyRelationship( type == RelationshipType.REQUIRED_BY, object == genomeprop ),
				sum( r.getSubject().getValue() ) )

 	then 
		double numRequiredComponents = new Double(requiredRelations.size());
 		double fractionFilledComponents = (numRequiredComponents == 0) ? 0
								: numFilledComponents / numRequiredComponents;
  		System.out.println("Test calculation...");
   		System.out.println(numFilledComponents + "/" +
	  				numRequiredComponents + " = " +
	  				fractionFilledComponents + " " + 
	  				genomeprop.toString());

		modify( genomeprop ) {
			setRequired(numRequiredComponents),
			setFilled(numFilledComponents),
			setValue(fractionFilledComponents)
		};
		
		System.out.println(genomeprop.toStringReport());
end
